
const assert = require('node:assert/strict');
const fs = require('node:fs');
const zlib = require('node:zlib');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const page = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const cinematic = fs.readFileSync(path.join(root, 'assets', 'cinematic.js'), 'utf8');
const cinematicLoader = fs.readFileSync(path.join(root, 'assets', 'cinematic-loader.js'), 'utf8');
const styles = fs.readFileSync(path.join(root, 'assets', 'cinematic.css'), 'utf8');
const backup = fs.readFileSync(path.join(root, 'backup.js'), 'utf8');
const swimAction = JSON.parse(fs.readFileSync(path.join(root, 'assets', 'penguin-swim-action.json'), 'utf8'));
const compactRigEncoded = fs.readFileSync(path.join(root, 'assets', 'models', 'penguin-swim-rig-v2.json.gz.b64'), 'utf8').trim();
const compactRig = JSON.parse(zlib.gunzipSync(Buffer.from(compactRigEncoded, 'base64')).toString('utf8'));
const thirdPartyAssets = fs.readFileSync(path.join(root, 'THIRD_PARTY_ASSETS.md'), 'utf8');

assert.match(server, /three\.module\.js': 'https:\/\/cdn\.jsdelivr\.net\/npm\/three@0\.186\.0\/build\/three\.module\.js'/);
assert.match(server, /three\.core\.js': 'https:\/\/cdn\.jsdelivr\.net\/npm\/three@0\.186\.0\/build\/three\.core\.js'/);
assert.match(page, /href="\/assets\/cinematic\.css\?v=20260924-cinematic-v3"/);
assert.match(page, /src="\/assets\/cinematic-loader\.js\?v=20260924-cinematic-v13" defer/);
assert.doesNotMatch(page, /type="module" src="\/assets\/cinematic\.js/);
assert.match(page, /id="littleFeetCinematicJourney"/);
assert.match(page, /id="littleFeetCinematicCanvas"/);

assert.match(cinematic, /import \* as THREE from '\/vendor\/three\.module\.js'/);
assert.match(cinematic, /prefers-reduced-motion: reduce/);
assert.doesNotMatch(cinematic, /failIfMajorPerformanceCaveat\s*:/);
assert.doesNotMatch(cinematic, /canUseWebGL2/);
assert.match(cinematic, /powerPreference: 'default'/);
assert.match(cinematic, /webgl-renderer-unavailable/);
assert.match(cinematic, /qualityForDevice/);
assert.match(cinematic, /typeof window\.openWorkspace === 'function'/);
assert.match(cinematic, /accessibleNavTarget/);
assert.match(cinematic, /document\.hidden/);
assert.match(cinematic, /CylinderGeometry\(3\.45, 3\.05, \.62/);
assert.match(cinematic, /camera\.position\.set\(\.8, 3\.8, 11\.8\)/);
assert.match(cinematic, /firstFrameRendered/);
assert.match(cinematic, /webglcontextlost/);
assert.match(cinematic, /cinematic render failed/);
assert.match(cinematic, /dashboardSection/);
assert.match(cinematic, /rect\.width < 2 \|\| rect\.height < 2/);
assert.match(cinematic, /ResizeObserver/);
assert.match(cinematic, /MutationObserver/);
assert.match(cinematic, /dashboard\.classList\.contains\('hidden'\)/);
assert.match(cinematic, /refreshStationTargets/);
assert.match(cinematic, /diveKeyframes/);
assert.match(cinematic, /sampleDivePath/);
assert.match(cinematic, /mascot\.position\.y \+ 4\.35/);
assert.match(cinematic, /headRig/);
assert.match(cinematic, /requestedYaw = lerp\(pointer\.smoothX \* 1\.02/);
assert.match(cinematic, /eyeX = pointer\.smoothX \* \.155/);
assert.match(cinematic, /window\.addEventListener\('pointermove'/);
assert.match(cinematic, /pointer\.activity/);
assert.match(cinematic, /bodyBreath/);
assert.match(cinematic, /anticipation/);
assert.match(cinematic, /chirpOpen/);
assert.match(cinematic, /createFishSchool/);
assert.match(cinematic, /createMantaRay/);
assert.match(cinematic, /createKelpPatch/);
assert.match(cinematic, /createGlowReef/);
assert.match(cinematic, /createCausticBeams/);
assert.match(cinematic, /createDepthMist/);
assert.match(cinematic, /createDepthTerrace/);
assert.match(cinematic, /createDepthBackdrop/);
assert.match(cinematic, /depthBackdrop\.userData/);
assert.match(cinematic, /strokeCycle/);
assert.match(cinematic, /sampleSourceSwimBone/);
assert.match(cinematic, /sourceSwimAction/);
assert.match(cinematic, /uploaded-riley-action/);
assert.match(cinematic, /authoredLeftZ/);
assert.match(cinematic, /authoredRightZ/);
assert.match(cinematic, /sourceUpperRight/);
assert.match(cinematic, /sourceUpperLeft/);
assert.match(cinematic, /leftFlipperMesh\.rotation\.x/);
assert.match(cinematic, /rightFlipperMesh\.rotation\.z/);
assert.match(cinematic, /authoredBodyPitch/);
assert.match(cinematic, /sourceBlend.*1\.12/s);
assert.equal(swimAction.schema, 'little-feet-penguin-action-v1');
assert.equal(swimAction.source.action, 'ArmatureAction');
assert.equal(swimAction.source.fps, 24);
assert.equal(swimAction.source.frameEnd, 40);
assert.equal(swimAction.mapping.leftFlipperRoot, 'Bone.010');
assert.equal(swimAction.mapping.rightFlipperRoot, 'Bone.005');
assert.ok(Array.isArray(swimAction.bones['Bone.010'].rotationDeltaEulerXYZ));
assert.equal(swimAction.mapping.upperRight, 'Bone.008');
assert.equal(swimAction.mapping.upperLeft, 'Bone.013');
assert.equal(compactRig.f, 'lf-rig2');
assert.equal(compactRig.b.length, 10);
assert.equal(compactRig.p.length, 3);
assert.equal(compactRig.a.b.length, 10);
assert.equal(compactRig.a.t.length, 9);
assert.match(compactRig.src.url, /penguin-swimming-855d54f1e67a4564aac7871b30ef687d/);
assert.match(thirdPartyAssets, /Riley \/ rkuhlf/);
assert.match(thirdPartyAssets, /Creative Commons Attribution/);
assert.match(cinematic, /powerStroke/);
assert.match(cinematic, /recoveryStroke/);
assert.match(cinematic, /firstStrokeBurst/);
assert.match(cinematic, /entryHeading/);
assert.match(cinematic, /travelHeading/);
assert.match(cinematic, /diveFocus/);
assert.match(cinematic, /deepening = smoothstep/);
assert.match(cinematic, /nearestStationPose/);
assert.match(cinematic, /samplePathMotion/);
assert.match(cinematic, /stationHold/);
assert.match(cinematic, /chestRig/);
assert.match(cinematic, /leftShoulder/);
assert.match(cinematic, /tailRig/);
assert.match(cinematic, /mascotTrail/);
assert.match(cinematic, /splashRing/);
assert.match(cinematic, /animateWorld/);
assert.match(cinematic, /animateBubbleField/);
assert.match(cinematic, /panicTarget/);
assert.match(cinematic, /playWaterSplash/);
assert.match(cinematic, /splashSoundArmed/);
assert.match(cinematic, /Rigid shoulder-driven flippers/);
assert.match(cinematic, /Feet tuck against the body at speed/);
assert.match(cinematic, /station-hover/);
assert.match(cinematic, /stage\.dataset\.mascotBehavior/);
assert.match(cinematic, /progress >= station\.at - \.003/);
assert.match(cinematic, /at: 0\.225,x:\s+2\.20/);
assert.match(cinematic, /at: 0\.24, x:\s+2\.72, y: -0\.90/);
assert.match(cinematic, /headRigBase/);
assert.match(cinematic, /neckClearance/);
assert.match(cinematic, /clamp\(requestedYaw, -\.72, \.72\)/);
assert.match(cinematic, /sampleDivePath\(\.235\)/);
assert.match(cinematic, /lowerBeak/);
assert.match(cinematic, /surfaceFront > \.82/);
assert.match(cinematic, /setCinematicAudioMix/);
assert.match(cinematic, /ensureCinematicAudio/);
assert.match(cinematic, /masterTarget = muted \? 0\.0001 : 0\.12/);
assert.match(cinematic, /window\.addEventListener\('littlefeet:audiochange'/);
assert.match(backup, /window\.getPortalAudioContext = getPortalAudioContext/);
assert.match(backup, /window\.isPortalAudioMuted/);
assert.match(backup, /littlefeet:audiochange/);
assert.match(backup, /announcePortalAudioState\(\)/);
assert.match(cinematic, /eyeLBase/);
assert.match(cinematic, /playMascotChirp/);
assert.match(cinematic, /portalIntroThemePlaying/);
assert.match(cinematic, /stopPortalIntroTheme/);
assert.match(cinematic, /scheduleNextMascotChirp/);
assert.match(cinematic, /mascotChirpTimeline/);
assert.match(cinematic, /nextMascotChirpAt/);
assert.match(cinematic, /raw > \.012 && portalIntroThemePlaying\(\)/);
assert.match(cinematic, /littlefeet:introthemechange/);
assert.match(backup, /WELCOME_THEME_MAX_MS = 10000/);
assert.match(backup, /window\.isPortalIntroThemePlaying/);
assert.match(backup, /window\.stopPortalIntroTheme/);
assert.match(backup, /littlefeet:introthemechange/);
assert.match(backup, /10000\);/);
assert.match(cinematic, /lf_portal_audio_muted_last/);
assert.match(cinematic, /journey\.classList\.toggle\('is-active'/);
assert.match(styles, /cinematic-journey\.is-active \.cinematic-stage/);
assert.match(styles, /width: calc\(100vw - 260px\)/);
assert.match(styles, /#homeTab\.tab-content\.active/);
assert.match(styles, /transform: none !important/);
assert.match(cinematic, /fetch\('\/assets\/penguin-swim-action\.json\?v=20260924-swim-v1'/);
assert.doesNotMatch(cinematic, /fetch\(['"]https?:\/\//);
assert.doesNotMatch(cinematic, /innerHTML\s*=/);

assert.match(cinematicLoader, /dashboardSection/);
assert.match(cinematicLoader, /dashboard\.classList\.contains\('hidden'\)/);
assert.match(cinematicLoader, /MutationObserver/);
assert.match(cinematicLoader, /import\('\/assets\/cinematic\.js\?v=20260924-cinematic-v13'\)/);
assert.match(cinematicLoader, /cinematic-fallback/);
assert.doesNotMatch(cinematicLoader, /fetch\(/);
assert.doesNotMatch(cinematicLoader, /innerHTML\s*=/);

assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/);
assert.match(styles, /\.cinematic-fallback/);
assert.match(styles, /backdrop-filter/);

console.log('Cinematic navigation regression test passed.');
