
const assert = require('node:assert/strict');
const fs = require('node:fs');
const zlib = require('node:zlib');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const page = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const cinematic = fs.readFileSync(path.join(root, 'assets', 'cinematic.js'), 'utf8');
const cinematicLoader = fs.readFileSync(path.join(root, 'assets', 'cinematic-loader.js'), 'utf8');
const styles = fs.readFileSync(path.join(root, 'assets', 'cinematic.css'), 'utf8');
const backup = fs.readFileSync(path.join(root, 'backup.js'), 'utf8');
const swimAction = JSON.parse(fs.readFileSync(path.join(root, 'assets', 'penguin-swim-action.json'), 'utf8'));
const compactRigEncoded = fs.readFileSync(path.join(root, 'assets', 'models', 'penguin-swim-rig-v2.json.gz.b64'), 'utf8').trim();
const compactRig = JSON.parse(zlib.gunzipSync(Buffer.from(compactRigEncoded, 'base64')).toString('utf8'));
const thirdPartyAssets = fs.readFileSync(path.join(root, 'THIRD_PARTY_ASSETS.md'), 'utf8');

assert.match(server, /three\.module\.js': 'https:\/\/cdn\.jsdelivr\.net\/npm\/three@0\.186\.0\/build\/three\.module\.js'/);
assert.match(server, /three\.core\.js': 'https:\/\/cdn\.jsdelivr\.net\/npm\/three@0\.186\.0\/build\/three\.core\.js'/);
assert.match(page, /href="\/assets\/cinematic\.css\?v=20260924-cinematic-v3"/);
assert.match(page, /src="\/assets\/cinematic-loader\.js\?v=20260924-cinematic-v30" defer/);
assert.doesNotMatch(page, /type="module" src="\/assets\/cinematic\.js/);
assert.match(page, /id="littleFeetCinematicJourney"/);
assert.match(page, /id="littleFeetCinematicCanvas"/);

assert.match(cinematic, /import \* as THREE from '\/vendor\/three\.module\.js'/);
assert.match(cinematic, /prefers-reduced-motion: reduce/);
assert.doesNotMatch(cinematic, /getContext\(['"]webgl2/);
assert.doesNotMatch(cinematic, /canUseWebGL2/);
assert.match(cinematic, /powerPreference: 'default'/);
assert.match(cinematic, /webgl-renderer-unavailable/);
assert.match(cinematic, /PlaneGeometry\(44, 44, 32, 32\)/);
assert.match(cinematic, /new THREE\.ShaderMaterial/);
assert.match(cinematic, /safe-webgl-v7-directional-swim-idle/);
assert.match(cinematic, /water\.material\.uniforms\.uTime\.value = time/);
assert.doesNotMatch(cinematic, /computeVertexNormals\(\)/);
assert.doesNotMatch(cinematic, /new THREE\.PointLight\(color, 4\.2, 8, 2\)/);
assert.doesNotMatch(cinematic, /new THREE\.PointLight\(color, 5\.5, 9, 2\)/);
assert.match(cinematic, /markCinematicActivity/);
assert.match(cinematic, /let stageRect = null/);
assert.match(cinematic, /refreshJourneyMetrics/);
assert.match(cinematic, /journeyExitHold = Math\.min\(window\.innerHeight \* 1\.10, totalTravel \* \.22\)/);
assert.match(cinematic, /journeyEnd = journeyTop \+ totalTravel/);
assert.match(cinematic, /exitHoldActive/);
assert.match(cinematic, /insideJourney/);
assert.match(cinematic, /driftBase/);
assert.doesNotMatch(cinematic, /attr\.array\[offset\] = base\[offset\]/);
assert.match(cinematic, /const clearColorScratch = new THREE\.Color\(\)/);
assert.match(cinematic, /let waterInterval = 1 \/ 15/);
assert.match(cinematic, /waterInterval = 1 \/ 8/);
assert.match(cinematic, /waterInterval = 1 \/ 12/);
assert.match(cinematic, /waterInterval = 1 \/ 15/);
assert.match(cinematic, /let worldInterval = 1 \/ 24/);
assert.match(cinematic, /worldInterval = 1 \/ 10/);
assert.match(cinematic, /worldInterval = 1 \/ 15/);
assert.match(cinematic, /worldInterval = 1 \/ 20/);
assert.match(cinematic, /let bubbleInterval = 1 \/ 20/);
assert.match(cinematic, /bubbleInterval = 1 \/ 8/);
assert.match(cinematic, /bubbleInterval = 1 \/ 12/);
assert.match(cinematic, /bubbleInterval = 1 \/ 16/);
assert.match(cinematic, /mist\.position\.x = Math\.sin/);
assert.doesNotMatch(cinematic, /positions\.needsUpdate = true;/);
assert.match(cinematic, /stage\.dataset\.cinematicQuality = quality/);
assert.match(cinematic, /SCENE_DETAIL = 'high'/);
assert.match(cinematic, /performanceMode = 'adaptive-frame-time-v2'/);
assert.match(cinematic, /let renderFpsCap = 30/);
assert.match(cinematic, /stage\.dataset\.renderFpsCap = String\(renderFpsCap\)/);
assert.match(cinematic, /backgroundPause = 'offscreen-hard-stop-v2'/);
assert.match(cinematic, /compressionProfile = 'safe-webgl-v7-directional-swim-idle'/);
assert.match(cinematic, /IntersectionObserver/);
assert.match(cinematic, /renderer\.setAnimationLoop\(null\)/);
assert.match(cinematic, /renderer\.setAnimationLoop\(render\)/);
assert.match(cinematic, /cinematicRuntime = 'paused'/);
assert.match(cinematic, /cinematicRuntime = 'running'/);
assert.match(cinematic, /journeyInViewport/);
assert.match(cinematic, /homeObserver/);
assert.match(cinematic, /runtimeDashboardObserver/);
assert.match(cinematic, /averageMs > 24/);
assert.match(cinematic, /averageMs > 16/);
assert.match(cinematic, /averageMs < 11/);
assert.match(cinematic, /applyPerformanceTier\('enhanced'\)/);
assert.match(cinematic, /workStart = performance\.now\(\)/);
assert.match(cinematic, /let maxRenderPixels = 1280 \* 720/);
assert.match(cinematic, /maxRenderPixels = 960 \* 540/);
assert.match(cinematic, /maxRenderPixels = 1152 \* 648/);
assert.match(cinematic, /classifyViewport/);
assert.match(cinematic, /viewportClass/);
assert.match(cinematic, /devicePixelRatio/);
assert.match(cinematic, /fpsCapForRefresh/);
assert.match(cinematic, /samples\.length < 24/);
assert.match(cinematic, /displayRefreshHz/);
assert.match(cinematic, /window\.visualViewport\?\.addEventListener\('resize'/);
assert.match(cinematic, /renderPixelRatioTarget = \.62/);
assert.match(cinematic, /renderPixelRatioTarget = \.76/);
assert.match(cinematic, /renderPixelRatioTarget = \.88/);
assert.match(cinematic, /pixelBudgetRatio = Math\.sqrt\(maxRenderPixels \/ cssPixels\)/);
assert.match(cinematic, /displayPixelRatioLimit/);
assert.match(cinematic, /activityAgeMs > 3500/);
assert.match(cinematic, /effectiveFpsCap = activityAgeMs > 900 \? 12 : renderFpsCap/);
assert.match(cinematic, /cinematicIdle = 'frozen'/);
assert.match(cinematic, /cinematicIdle = 'active'/);
assert.match(cinematic, /minFrameMs = 1000 \/ effectiveFpsCap/);
assert.match(cinematic, /cinematicBatching = 'instanced-v1'/);
assert.match(cinematic, /mergeStaticGeometries/);
assert.match(cinematic, /getSharedJellyTentacleGeometry/);
assert.match(cinematic, /getSharedGeometry\('jellyBell'/);
assert.match(cinematic, /getSharedGeometry\('stationRingOuter'/);
assert.match(cinematic, /getSharedGeometry\('fishBody'/);
assert.match(cinematic, /buckets = \[\[\], \[\], \[\]\]/);
assert.match(cinematic, /new THREE\.InstancedMesh\(bodyGeometry, bodyMaterial, count\)/);
assert.match(cinematic, /new THREE\.InstancedMesh\(rockGeometry, baseMaterial, 11\)/);
assert.match(cinematic, /new THREE\.InstancedMesh\(new THREE\.IcosahedronGeometry\(1, 1\), silhouette, rockCount\)/);
assert.match(cinematic, /typeof window\.openWorkspace === 'function'/);
assert.match(cinematic, /accessibleNavTarget/);
assert.match(cinematic, /document\.hidden/);
assert.match(cinematic, /CylinderGeometry\(3\.45, 3\.05, \.62/);
assert.match(cinematic, /camera\.position\.set\(\.8, 3\.8, 11\.8\)/);
assert.match(cinematic, /firstFrameRendered/);
assert.match(cinematic, /webglcontextlost/);
assert.match(cinematic, /cinematic render failed/);
assert.match(cinematic, /dashboardSection/);
assert.match(cinematic, /rect\.width < 2 \|\| rect\.height < 2/);
assert.match(cinematic, /ResizeObserver/);
assert.match(cinematic, /MutationObserver/);
assert.match(cinematic, /dashboard\.classList\.contains\('hidden'\)/);
assert.match(cinematic, /refreshStationTargets/);
assert.match(cinematic, /diveKeyframes/);
assert.match(cinematic, /sampleDivePath/);
assert.match(cinematic, /mascot\.position\.y \+ 4\.35/);
assert.match(cinematic, /headRig/);
assert.match(cinematic, /requestedYaw = lerp\(pointer\.smoothX \* 1\.02/);
assert.match(cinematic, /eyeX = pointer\.smoothX \* \.155/);
assert.match(cinematic, /window\.addEventListener\('pointermove'/);
assert.match(cinematic, /pointer\.activity/);
assert.match(cinematic, /bodyBreath/);
assert.match(cinematic, /anticipation/);
assert.match(cinematic, /chirpOpen/);
assert.match(cinematic, /createFishSchool/);
assert.match(cinematic, /createMantaRay/);
assert.match(cinematic, /createKelpPatch/);
assert.match(cinematic, /createGlowReef/);
assert.match(cinematic, /createCausticBeams/);
assert.match(cinematic, /createDepthMist/);
assert.match(cinematic, /createDepthTerrace/);
assert.match(cinematic, /createDepthBackdrop/);
assert.match(cinematic, /depthBackdrop\.userData/);
assert.match(cinematic, /strokeCycle/);
assert.match(cinematic, /procedural-optimized/);
assert.match(cinematic, /penguin-calls-sprite\.mp3\?v=20260924-call-v1/);
assert.match(cinematic, /penguinCallSegments/);
assert.match(cinematic, /Math\.floor\(Math\.random\(\) \* penguinCallSegments\.length\)/);
assert.match(cinematic, /activePenguinCallUntil/);
assert.match(cinematic, /source\.start\(ctx\.currentTime, segment\.offset, duration\)/);
assert.match(cinematic, /minGap = underwater \? 3200 : 2600/);
assert.doesNotMatch(cinematic, /\[760, 1040, 880\]/);
assert.doesNotMatch(cinematic, /sourceBlend/);
assert.doesNotMatch(cinematic, /sourceBodyLower/);
assert.doesNotMatch(cinematic, /sourceRightRoot/);
assert.doesNotMatch(cinematic, /sourceLeftRoot/);
assert.doesNotMatch(cinematic, /sourceUpperRight/);
assert.doesNotMatch(cinematic, /sampleSourceSwimBone/);
assert.doesNotMatch(cinematic, /fetch\('\/assets\/penguin-swim-action\.json/);
assert.equal(swimAction.schema, 'little-feet-penguin-action-v1');
assert.equal(swimAction.source.action, 'ArmatureAction');
assert.equal(swimAction.source.fps, 24);
assert.equal(swimAction.source.frameEnd, 40);
assert.equal(swimAction.mapping.leftFlipperRoot, 'Bone.010');
assert.equal(swimAction.mapping.rightFlipperRoot, 'Bone.005');
assert.ok(Array.isArray(swimAction.bones['Bone.010'].rotationDeltaEulerXYZ));
assert.equal(swimAction.mapping.upperRight, 'Bone.008');
assert.equal(swimAction.mapping.upperLeft, 'Bone.013');
assert.equal(compactRig.f, 'lf-rig2');
assert.equal(compactRig.b.length, 10);
assert.equal(compactRig.p.length, 3);
assert.equal(compactRig.a.b.length, 10);
assert.equal(compactRig.a.t.length, 9);
assert.match(compactRig.src.url, /penguin-swimming-855d54f1e67a4564aac7871b30ef687d/);
assert.match(thirdPartyAssets, /Riley \/ rkuhlf/);
assert.match(thirdPartyAssets, /Creative Commons Attribution/);
assert.match(cinematic, /powerStroke/);
assert.match(cinematic, /recoveryStroke/);
assert.match(cinematic, /firstStrokeBurst/);
assert.match(cinematic, /entryHeading/);
assert.match(cinematic, /travelHeading/);
assert.match(cinematic, /diveFocus/);
assert.match(cinematic, /deepening = smoothstep/);
assert.match(cinematic, /nearestStationPose/);
assert.match(cinematic, /samplePathMotion/);
assert.match(cinematic, /let scrollDirection = 1/);
assert.match(cinematic, /progressDelta > 0 \? 1 : -1/);
assert.match(cinematic, /travelSign = scrollDirection < -\.12 \? -1 : 1/);
assert.match(cinematic, /directedMotion\.pitch/);
assert.match(cinematic, /directedMotion\.yaw/);
assert.match(cinematic, /directedMotion\.bank/);
assert.match(cinematic, /calmIdle/);
assert.match(cinematic, /idleSway/);
assert.match(cinematic, /idleNod/);
assert.match(cinematic, /idleFlipperQuirk/);
assert.match(cinematic, /idleTailTick/);
assert.match(cinematic, /stationHold/);
assert.match(cinematic, /chestRig/);
assert.match(cinematic, /leftShoulder/);
assert.match(cinematic, /tailRig/);
assert.match(cinematic, /mascotTrail/);
assert.match(cinematic, /splashRing/);
assert.match(cinematic, /animateWorld/);
assert.match(cinematic, /animateBubbleField/);
assert.match(cinematic, /panicTarget/);
assert.match(cinematic, /playWaterSplash/);
assert.match(cinematic, /splashSoundArmed/);
assert.match(cinematic, /Rigid shoulder-driven flippers/);
assert.match(cinematic, /Feet tuck against the body at speed/);
assert.match(cinematic, /station-hover/);
assert.match(cinematic, /stage\.dataset\.mascotBehavior/);
assert.match(cinematic, /progress >= station\.at - \.003/);
assert.match(cinematic, /at: 0\.225,x:\s+2\.20/);
assert.match(cinematic, /at: 0\.24, x:\s+2\.72, y: -0\.90/);
assert.match(cinematic, /headRigBase/);
assert.match(cinematic, /neckClearance/);
assert.match(cinematic, /clamp\(requestedYaw, -\.72, \.72\)/);
assert.match(cinematic, /sampleDivePath\(\.235\)/);
assert.match(cinematic, /lowerBeak/);
assert.match(cinematic, /surfaceFront > \.82/);
assert.match(cinematic, /setCinematicAudioMix/);
assert.match(cinematic, /ensureCinematicAudio/);
assert.match(cinematic, /masterTarget = muted \? 0\.0001 : 0\.12/);
assert.match(cinematic, /window\.addEventListener\('littlefeet:audiochange'/);
assert.match(backup, /window\.getPortalAudioContext = getPortalAudioContext/);
assert.match(backup, /window\.isPortalAudioMuted/);
assert.match(backup, /littlefeet:audiochange/);
assert.match(backup, /announcePortalAudioState\(\)/);
assert.match(cinematic, /eyeLBase/);
assert.match(cinematic, /playMascotChirp/);
assert.match(cinematic, /portalIntroThemePlaying/);
assert.match(cinematic, /stopPortalIntroTheme/);
assert.match(cinematic, /scheduleNextMascotChirp/);
assert.match(cinematic, /mascotChirpTimeline/);
assert.match(cinematic, /nextMascotChirpAt/);
assert.match(cinematic, /raw > \.012 && portalIntroThemePlaying\(\)/);
assert.match(cinematic, /littlefeet:introthemechange/);
assert.match(backup, /WELCOME_THEME_MAX_MS = 10000/);
assert.match(backup, /window\.isPortalIntroThemePlaying/);
assert.match(backup, /window\.stopPortalIntroTheme/);
assert.match(backup, /littlefeet:introthemechange/);
assert.match(backup, /10000\);/);
assert.match(cinematic, /lf_portal_audio_muted_last/);
assert.match(cinematic, /journey\.classList\.toggle\('is-active'/);
assert.match(styles, /cinematic-journey\.is-active \.cinematic-stage/);
assert.match(styles, /height: 100dvh/);
assert.match(styles, /@media \(max-height: 720px\)/);
assert.match(styles, /@media \(max-height: 520px\) and \(orientation: landscape\)/);
assert.match(styles, /env\(safe-area-inset-top\)/);
assert.match(styles, /width: calc\(100vw - 260px\)/);
assert.match(styles, /#homeTab\.tab-content\.active/);
assert.match(styles, /transform: none !important/);
assert.doesNotMatch(cinematic, /fetch\(['"]https?:\/\//);
assert.doesNotMatch(cinematic, /innerHTML\s*=/);

assert.match(cinematicLoader, /dashboardSection/);
assert.match(cinematicLoader, /dashboard\.classList\.contains\('hidden'\)/);
assert.match(cinematicLoader, /MutationObserver/);
assert.match(cinematicLoader, /import\('\/assets\/cinematic\.js\?v=20260924-cinematic-v30'\)/);
assert.match(cinematicLoader, /cinematic-fallback/);
assert.doesNotMatch(cinematicLoader, /fetch\(/);
assert.doesNotMatch(cinematicLoader, /innerHTML\s*=/);

assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/);
assert.match(styles, /\.cinematic-fallback/);
assert.doesNotMatch(styles, /backdrop-filter/);

console.log('Cinematic navigation regression test passed.');
