
const assert = require('node:assert/strict');
const fs = require('node:fs');
const zlib = require('node:zlib');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const page = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const cinematic = fs.readFileSync(path.join(root, 'assets', 'cinematic.js'), 'utf8');
const cinematicLoader = fs.readFileSync(path.join(root, 'assets', 'cinematic-loader.js'), 'utf8');
const styles = fs.readFileSync(path.join(root, 'assets', 'cinematic.css'), 'utf8');
const backup = fs.readFileSync(path.join(root, 'backup.js'), 'utf8');
const swimAction = JSON.parse(fs.readFileSync(path.join(root, 'assets', 'penguin-swim-action.json'), 'utf8'));
const compactRigEncoded = fs.readFileSync(path.join(root, 'assets', 'models', 'penguin-swim-rig-v2.json.gz.b64'), 'utf8').trim();
const compactRig = JSON.parse(zlib.gunzipSync(Buffer.from(compactRigEncoded, 'base64')).toString('utf8'));
const thirdPartyAssets = fs.readFileSync(path.join(root, 'THIRD_PARTY_ASSETS.md'), 'utf8');
const pausedArtworkPath = path.join(root, 'assets', 'images', 'little-feet-cinematic-paused-school.avif');
const pausedArtwork = fs.readFileSync(pausedArtworkPath);
const pausedArtworkStat = fs.statSync(pausedArtworkPath);

assert.match(server, /three\.module\.js': 'https:\/\/cdn\.jsdelivr\.net\/npm\/three@0\.186\.0\/build\/three\.module\.js'/);
assert.match(server, /three\.core\.js': 'https:\/\/cdn\.jsdelivr\.net\/npm\/three@0\.186\.0\/build\/three\.core\.js'/);
assert.match(page, /href="\/assets\/cinematic\.css\?v=20260925-cinematic-v10"/);
assert.match(page, /src="\/assets\/cinematic-loader\.js\?v=20260925-cinematic-v45" defer/);
assert.doesNotMatch(page, /type="module" src="\/assets\/cinematic\.js/);
assert.match(page, /id="littleFeetCinematicJourney"/);
assert.match(page, /id="littleFeetCinematicCanvas"/);

assert.match(cinematic, /import \* as THREE from '\/vendor\/three\.module\.js'/);
assert.match(cinematic, /prefers-reduced-motion: reduce/);
assert.doesNotMatch(cinematic, /getContext\(['"]webgl2/);
assert.doesNotMatch(cinematic, /canUseWebGL2/);
assert.match(cinematic, /powerPreference: 'default'/);
assert.match(cinematic, /webgl-renderer-unavailable/);
assert.match(cinematic, /safe-webgl-v16-static-water-depth-glow/);
assert.match(cinematic, /LittleFeetMascotV3/);
assert.match(cinematic, /createMicroReliefTexture/);
assert.match(cinematic, /new THREE\.CanvasTexture/);
assert.match(cinematic, /new THREE\.Bone\(\)/);
assert.match(cinematic, /bone-limits-scene-spheres-v1/);
assert.match(cinematic, /resolveSceneCollision/);
assert.match(cinematic, /createPearBodyGeometry/);
assert.match(cinematic, /createWebbedFootGeometry/);
assert.match(cinematic, /addFeatherVertexColors/);
assert.match(cinematic, /new THREE\.LatheGeometry/);
assert.match(cinematic, /headRig\.position\.set\(0, \.76, \.03\)/);
assert.match(cinematic, /little-feet-mascot-v3/);
assert.match(cinematic, /video-reference-v3/);
assert.match(cinematic, /const lens = new THREE\.MeshBasicMaterial/);
assert.doesNotMatch(cinematic, /procedural-optimized/);
assert.doesNotMatch(cinematic, /new THREE\.CapsuleGeometry\(\.18, 1\.05/);
assert.match(cinematic, /roughenIceGeometry[\s\S]*geometry\.computeVertexNormals\(\)/);
assert.match(cinematic, /createStaticWaterSurface/);
assert.match(cinematic, /new THREE\.PlaneGeometry\(64, 64, 1, 1\)/);
assert.match(cinematic, /waterModel = 'single-plane-bump-v1'/);
assert.match(cinematic, /waterSurface\.userData\.relief\.offset\.x/);
assert.doesNotMatch(cinematic, /new THREE\.ShaderMaterial/);
assert.match(cinematic, /new THREE\.PointLight\(color, 2\.2, 8\.5, 2\)/);
assert.match(cinematic, /emissiveIntensity = 5\.2/);
assert.match(cinematic, /markCinematicActivity/);
assert.match(cinematic, /let stageRect = null/);
assert.match(cinematic, /refreshJourneyMetrics/);
assert.match(cinematic, /journeyExitHold = Math\.min\(window\.innerHeight \* 1\.10, totalTravel \* \.22\)/);
assert.match(cinematic, /journeyEnd = journeyTop \+ totalTravel/);
assert.match(cinematic, /exitHoldActive/);
assert.match(cinematic, /insideJourney/);
assert.match(cinematic, /driftBase/);
assert.doesNotMatch(cinematic, /attr\.array\[offset\] = base\[offset\]/);
assert.match(cinematic, /const clearColorScratch = new THREE\.Color\(\)/);
assert.match(cinematic, /let worldInterval = 1 \/ 24/);
assert.match(cinematic, /worldInterval = 1 \/ 10/);
assert.match(cinematic, /worldInterval = 1 \/ 15/);
assert.match(cinematic, /worldInterval = 1 \/ 20/);
assert.match(cinematic, /let bubbleInterval = 1 \/ 20/);
assert.match(cinematic, /bubbleInterval = 1 \/ 8/);
assert.match(cinematic, /bubbleInterval = 1 \/ 12/);
assert.match(cinematic, /bubbleInterval = 1 \/ 16/);
assert.doesNotMatch(cinematic, /mist\.position\.x = Math\.sin/);
assert.doesNotMatch(cinematic, /positions\.needsUpdate = true;/);
assert.match(cinematic, /stage\.dataset\.cinematicQuality = quality/);
assert.match(cinematic, /SCENE_DETAIL = 'medium'/);
assert.match(cinematic, /performanceMode = 'true-capped-scheduler-v3'/);
assert.match(cinematic, /let renderFpsCap = 24/);
assert.match(cinematic, /stage\.dataset\.renderFpsCap = String\(renderFpsCap\)/);
assert.match(cinematic, /backgroundPause = 'offscreen-hard-stop-v2'/);
assert.match(cinematic, /compressionProfile = 'safe-webgl-v16-static-water-depth-glow'/);
assert.match(cinematic, /IntersectionObserver/);
assert.match(cinematic, /cinematicRuntime = 'paused'/);
assert.match(cinematic, /cinematicRuntime = 'running'/);
assert.match(cinematic, /journeyInViewport/);
assert.match(cinematic, /homeObserver/);
assert.match(cinematic, /runtimeDashboardObserver/);
assert.doesNotMatch(cinematic, /averageMs > 24/);
assert.doesNotMatch(cinematic, /averageMs > 16/);
assert.doesNotMatch(cinematic, /averageMs < 11/);
assert.match(cinematic, /applyPerformanceTier\('enhanced'\)/);
assert.match(cinematic, /workStart = performance\.now\(\)/);
assert.match(cinematic, /let maxRenderPixels = 1152 \* 648/);
assert.match(cinematic, /maxRenderPixels = 960 \* 540/);
assert.match(cinematic, /maxRenderPixels = 1152 \* 648/);
assert.match(cinematic, /classifyViewport/);
assert.match(cinematic, /viewportClass/);
assert.match(cinematic, /devicePixelRatio/);
assert.match(cinematic, /fpsCapForRefresh/);
assert.match(cinematic, /samples\.length < 24/);
assert.match(cinematic, /displayRefreshHz/);
assert.match(cinematic, /window\.visualViewport\?\.addEventListener\('resize'/);
assert.match(cinematic, /renderPixelRatioTarget = \.56/);
assert.match(cinematic, /renderPixelRatioTarget = \.66/);
assert.match(cinematic, /renderPixelRatioTarget = \.76/);
assert.match(cinematic, /pixelBudgetRatio = Math\.sqrt\(maxRenderPixels \/ cssPixels\)/);
assert.match(cinematic, /antialias: false/);
assert.match(cinematic, /if \(perfFrameCount < 24\) return/);
assert.match(cinematic, /if \(averageMs > 20\)/);
assert.match(cinematic, /if \(averageMs > 13\)/);
assert.match(cinematic, /displayPixelRatioLimit/);
assert.match(cinematic, /activityAgeMs > 3500/);
assert.match(cinematic, /cinematicIdle = 'frozen'/);
assert.match(cinematic, /cinematicIdle = 'active'/);
assert.match(cinematic, /cinematicBatching = 'hero-only-v2'/);
assert.match(cinematic, /getSharedGeometry\('stationRingOuter'/);
assert.match(cinematic, /typeof window\.openWorkspace === 'function'/);
assert.match(cinematic, /accessibleNavTarget/);
assert.match(cinematic, /document\.hidden/);
assert.match(cinematic, /CylinderGeometry\(3\.45, 3\.05, \.62/);
assert.match(cinematic, /camera\.position\.set\(\.8, 3\.8, 11\.8\)/);
assert.match(cinematic, /firstFrameRendered/);
assert.match(cinematic, /webglcontextlost/);
assert.match(cinematic, /cinematic render failed/);
assert.match(cinematic, /dashboardSection/);
assert.match(cinematic, /rect\.width < 2 \|\| rect\.height < 2/);
assert.match(cinematic, /ResizeObserver/);
assert.match(cinematic, /MutationObserver/);
assert.match(cinematic, /dashboard\.classList\.contains\('hidden'\)/);
assert.match(cinematic, /refreshStationTargets/);
assert.match(cinematic, /diveKeyframes/);
assert.match(cinematic, /sampleDivePath/);
assert.match(cinematic, /mascot\.position\.y \+ 4\.35/);
assert.match(cinematic, /headRig/);
assert.match(cinematic, /const requestedYaw = lerp\(/);
assert.match(cinematic, /pointer\.smoothX \* 1\.02 \* gazeBoost/);
assert.match(cinematic, /eyeX = pointer\.smoothX \* \.155/);
assert.match(cinematic, /window\.addEventListener\('pointermove'/);
assert.match(cinematic, /pointer\.activity/);
assert.match(cinematic, /bodyBreath/);
assert.match(cinematic, /anticipation/);
assert.match(cinematic, /chirpOpen/);
assert.match(cinematic, /strokeCycle/);
assert.match(cinematic, /penguin-calls-sprite\.mp3\?v=20260924-call-v1/);
assert.match(cinematic, /penguinCallSegments/);
assert.match(cinematic, /Math\.floor\(Math\.random\(\) \* penguinCallSegments\.length\)/);
assert.match(cinematic, /activePenguinCallUntil/);
assert.match(cinematic, /source\.start\(ctx\.currentTime, segment\.offset, duration\)/);
assert.match(cinematic, /minGap = underwater \? 3200 : 2600/);
assert.doesNotMatch(cinematic, /\[760, 1040, 880\]/);
assert.doesNotMatch(cinematic, /sourceBlend/);
assert.doesNotMatch(cinematic, /sourceBodyLower/);
assert.doesNotMatch(cinematic, /sourceRightRoot/);
assert.doesNotMatch(cinematic, /sourceLeftRoot/);
assert.doesNotMatch(cinematic, /sourceUpperRight/);
assert.doesNotMatch(cinematic, /sampleSourceSwimBone/);
assert.doesNotMatch(cinematic, /fetch\('\/assets\/penguin-swim-action\.json/);
assert.equal(swimAction.schema, 'little-feet-penguin-action-v1');
assert.equal(swimAction.source.action, 'ArmatureAction');
assert.equal(swimAction.source.fps, 24);
assert.equal(swimAction.source.frameEnd, 40);
assert.equal(swimAction.mapping.leftFlipperRoot, 'Bone.010');
assert.equal(swimAction.mapping.rightFlipperRoot, 'Bone.005');
assert.ok(Array.isArray(swimAction.bones['Bone.010'].rotationDeltaEulerXYZ));
assert.equal(swimAction.mapping.upperRight, 'Bone.008');
assert.equal(swimAction.mapping.upperLeft, 'Bone.013');
assert.equal(compactRig.f, 'lf-rig2');
assert.equal(compactRig.b.length, 10);
assert.equal(compactRig.p.length, 3);
assert.equal(compactRig.a.b.length, 10);
assert.equal(compactRig.a.t.length, 9);
assert.match(compactRig.src.url, /penguin-swimming-855d54f1e67a4564aac7871b30ef687d/);
assert.match(thirdPartyAssets, /Riley \/ rkuhlf/);
assert.match(thirdPartyAssets, /Creative Commons Attribution/);
assert.match(cinematic, /powerStroke/);
assert.match(cinematic, /recoveryStroke/);
assert.match(cinematic, /firstStrokeBurst/);
assert.match(cinematic, /entryHeading/);
assert.match(cinematic, /travelHeading/);
assert.match(cinematic, /diveFocus/);
assert.match(cinematic, /deepening = smoothstep/);
assert.match(cinematic, /nearestStationPose/);
assert.match(cinematic, /samplePathMotion/);
assert.match(cinematic, /let scrollDirection = 1/);
assert.match(cinematic, /progressDelta > 0 \? 1 : -1/);
assert.match(cinematic, /travelSign = scrollDirection < -\.12 \? -1 : 1/);
assert.match(cinematic, /directedMotion\.pitch/);
assert.match(cinematic, /directedMotion\.yaw/);
assert.match(cinematic, /directedMotion\.bank/);
assert.match(cinematic, /calmIdle/);
assert.match(cinematic, /idleSway/);
assert.match(cinematic, /idleNod/);
assert.match(cinematic, /idleFlipperQuirk/);
assert.match(cinematic, /idleTailTick/);
assert.match(cinematic, /FISH_SPRITE_SRC/);
assert.match(cinematic, /Alosa_alosa\.png\/330px-Alosa_alosa\.png/);
assert.match(cinematic, /populateFishSchools/);
assert.match(cinematic, /cinematic-fish-sprite/);
assert.match(cinematic, /fishSchoolLayouts/);
assert.match(page, /id="cinematicPause"/);
assert.match(page, /class="cinematic-paused-picture"/);
assert.match(page, /little-feet-cinematic-paused-school\.avif/);
assert.match(styles, /\.cinematic-paused-picture \{[\s\S]*z-index: 3/);
assert.match(styles, /\.cinematic-journey\.is-user-paused \.cinematic-paused-picture \{[\s\S]*opacity: 1[\s\S]*visibility: visible/);
assert.match(styles, /\.cinematic-journey\.is-user-paused \.cinematic-loading \{[\s\S]*display: none/);
assert.match(styles, /\.cinematic-journey\.is-user-paused \.cinematic-copy,[\s\S]*\.cinematic-progress-shell/);
assert.ok(pausedArtworkStat.size > 40000 && pausedArtworkStat.size < 150000, 'Paused artwork must stay compact while retaining useful detail.');
assert.match(pausedArtwork.subarray(0, 32).toString('ascii'), /ftypavif/);
assert.match(page, /id="cinematicDepthBackdrop"/);
assert.match(page, /id="cinematicFish2dA"/);
assert.match(page, /id="cinematicFish2dB"/);
assert.match(page, /id="cinematicJelly2dA"/);
assert.match(page, /id="cinematicJelly2dB"/);
assert.match(page, /id="cinematicManta2d"/);
assert.match(page, /cinematic-surface-air/);
assert.match(page, /cinematic-water-surface/);
assert.match(page, /cinematic-water-current/);
assert.match(styles, /\.cinematic-surface-air/);
assert.match(styles, /\.cinematic-water-surface/);
assert.match(styles, /\.cinematic-water-current/);
assert.match(styles, /--depth-dim/);
assert.match(styles, /--panel-glow/);
assert.match(styles, /cinematicSurfaceDrift/);
assert.match(styles, /cinematicCurrentDrift/);
assert.match(styles, /top: 39\.5%/);
assert.match(styles, /height: 60%/);
assert.match(styles, /cinematic-fish-2d-a \{[\s\S]*left: 1%;[\s\S]*top: 47%/);
assert.match(styles, /cinematic-jelly-2d-a \{ right: 12%; top: 51%/);
assert.match(styles, /rgba\(235,255,255,\.88\)/);
assert.doesNotMatch(cinematic, /createWater/);
assert.doesNotMatch(cinematic, /updateWater/);
assert.doesNotMatch(cinematic, /water\.material/);
assert.doesNotMatch(cinematic, /new THREE\.ShaderMaterial/);
assert.doesNotMatch(cinematic, /waterInterval/);
assert.doesNotMatch(cinematic, /waterBudget/);
assert.doesNotMatch(page, /id="cinematicParallaxFar"/);
assert.doesNotMatch(page, /id="cinematicParallaxNear"/);
assert.doesNotMatch(page, /id="cinematicSeabed2d"/);
assert.match(page, /src="\/assets\/images\/little-feet-ocean-depth-1080\.webp"/);
assert.match(page, /min-width: 2200px/);
assert.match(page, /little-feet-ocean-depth-4k\.webp/);
assert.match(cinematic, /scheduleCinematicFrame/);
assert.match(cinematic, /scheduledFps/);
assert.match(cinematic, /return activityAgeMs > 900 \? Math\.min\(12, renderFpsCap\) : renderFpsCap/);
assert.match(cinematic, /window\.setTimeout/);
assert.match(cinematic, /window\.requestAnimationFrame/);
assert.match(cinematic, /window\.cancelAnimationFrame/);
assert.doesNotMatch(cinematic, /setAnimationLoop/);
assert.doesNotMatch(cinematic, /createCausticBeams/);
assert.doesNotMatch(cinematic, /depthBackdropImage\.offsetHeight/);
assert.match(cinematic, /depthImageTravel/);
assert.match(cinematic, /stopCinematicAudio/);
assert.doesNotMatch(styles, /cinematic-parallax-image/);
assert.doesNotMatch(styles, /cinematic-seabed-2d/);
assert.match(styles, /cinematic-jellyfish\.svg/);
assert.match(styles, /cinematic-manta\.svg/);
assert.match(styles, /\.cinematic-fish-sprite/);
assert.match(styles, /cinematicFishIndividual/);
assert.match(styles, /background: none/);
assert.match(styles, /mask-image: none/);
assert.doesNotMatch(styles, /Underwater_view_of_the_sardine_run/);
assert.doesNotMatch(styles, /Fish_school_%28Unsplash%29\.jpg/);
assert.doesNotMatch(styles, /cinematic-fish-school\.svg/);
assert.match(styles, /Jellyfish01\.jpg/);
assert.match(styles, /P2140268_Manta_Ray\.jpg/);
assert.match(styles, /mask-image/);
assert.doesNotMatch(cinematic, /createFishSchool/);
assert.doesNotMatch(cinematic, /createJellyfish/);
assert.doesNotMatch(cinematic, /mergeStaticGeometries/);
assert.doesNotMatch(cinematic, /getSharedJellyTentacleGeometry/);
assert.doesNotMatch(cinematic, /createMantaRay/);
assert.doesNotMatch(cinematic, /InstancedMesh/);
assert.doesNotMatch(cinematic, /DynamicDrawUsage/);
assert.doesNotMatch(cinematic, /penguin-feather/);
assert.doesNotMatch(cinematic, /ice-crystal/);
assert.doesNotMatch(cinematic, /TextureLoader/);
assert.match(cinematic, /safe-webgl-v16-static-water-depth-glow/);
assert.doesNotMatch(cinematic, /createDepthMist/);
assert.doesNotMatch(cinematic, /createDepthTerrace/);
assert.doesNotMatch(cinematic, /createDepthBackdrop/);
assert.match(cinematic, /safe-webgl-v16-static-water-depth-glow/);
assert.match(page, /little-feet-ocean-depth-4k\.webp/);
assert.match(page, /little-feet-ocean-depth-1080\.webp/);
assert.match(styles, /height: 680vh/);
assert.match(styles, /cinematic-depth-image/);
assert.doesNotMatch(styles, /cinematic-portrait-light/);
assert.doesNotMatch(styles, /cinematic-portrait-depth-lines/);
assert.match(styles, /cinematic-footer-actions/);
assert.match(cinematic, /lf_cinematic_paused/);
assert.match(cinematic, /cinematicUserPaused/);
assert.match(cinematic, /pausedScrollProgress/);
assert.match(cinematic, /journey\.classList\.remove\('is-active', 'is-after'\)/);
assert.match(cinematic, /window\.scrollTo\(\{ top: journeyTop \+ journeyTravel \* resumeProgress, behavior: 'auto' \}\)/);
assert.match(styles, /\.cinematic-journey\.is-user-paused \{[\s\S]*height: auto !important/);
assert.match(styles, /\.cinematic-journey\.is-user-paused \.cinematic-stage \{[\s\S]*position: relative !important/);
assert.match(cinematic, /paused-by-user/);
assert.match(cinematic, /activePenguinCallSource\.stop/);
assert.match(cinematic, /smoothProgress = damp\(smoothProgress, scrollProgress, 5\.0, dt\)/);
assert.match(cinematic, /depthBackdropImage\.style\.transform/);
assert.match(cinematic, /stationHold/);
assert.match(cinematic, /chestRig/);
assert.match(cinematic, /leftShoulder/);
assert.match(cinematic, /tailRig/);
assert.match(cinematic, /mascotTrail/);
assert.match(cinematic, /splashRing/);
assert.match(cinematic, /animateWorld/);
assert.match(cinematic, /animateBubbleField/);
assert.match(cinematic, /playWaterSplash/);
assert.match(cinematic, /splashSoundArmed/);
assert.match(cinematic, /Rigid shoulder-driven flippers/);
assert.match(cinematic, /Feet tuck against the body at speed/);
assert.match(cinematic, /station-hover/);
assert.match(cinematic, /stage\.dataset\.mascotBehavior/);
assert.match(cinematic, /progress >= station\.at - \.003/);
assert.match(cinematic, /at: 0\.225,x:\s+2\.20/);
assert.match(cinematic, /at: 0\.24, x:\s+2\.72, y: -0\.90/);
assert.match(cinematic, /headRigBase/);
assert.match(cinematic, /neckClearance/);
assert.match(cinematic, /data\.rigCollision\.headYaw/);
assert.match(cinematic, /sampleDivePath\(\.235\)/);
assert.match(cinematic, /lowerBeak/);
assert.match(cinematic, /surfaceFront > \.82/);
assert.match(cinematic, /setCinematicAudioMix/);
assert.match(cinematic, /ensureCinematicAudio/);
assert.match(cinematic, /masterTarget = muted \? 0\.0001 : 0\.12/);
assert.match(cinematic, /window\.addEventListener\('littlefeet:audiochange'/);
assert.match(backup, /window\.getPortalAudioContext = getPortalAudioContext/);
assert.match(backup, /window\.isPortalAudioMuted/);
assert.match(backup, /littlefeet:audiochange/);
assert.match(backup, /announcePortalAudioState\(\)/);
assert.match(cinematic, /eyeLBase/);
assert.match(cinematic, /playMascotChirp/);
assert.match(cinematic, /scheduleNextMascotChirp/);
assert.match(cinematic, /mascotChirpTimeline/);
assert.match(cinematic, /nextMascotChirpAt/);
assert.match(backup, /10000\);/);
assert.match(cinematic, /lf_portal_audio_muted_last/);
assert.match(cinematic, /journey\.classList\.toggle\('is-active'/);
assert.match(styles, /cinematic-journey\.is-active \.cinematic-stage/);
assert.match(styles, /height: 100dvh/);
assert.match(styles, /@media \(max-height: 720px\)/);
assert.match(styles, /@media \(max-height: 520px\) and \(orientation: landscape\)/);
assert.match(styles, /env\(safe-area-inset-top\)/);
assert.match(styles, /width: calc\(100vw - 260px\)/);
assert.match(styles, /#homeTab\.tab-content\.active/);
assert.match(styles, /transform: none !important/);
assert.doesNotMatch(cinematic, /fetch\(['"]https?:\/\//);
assert.doesNotMatch(cinematic, /innerHTML\s*=/);

assert.match(cinematicLoader, /dashboardSection/);
assert.match(cinematicLoader, /dashboard\.classList\.contains\('hidden'\)/);
assert.match(cinematicLoader, /MutationObserver/);
assert.match(cinematicLoader, /import\('\/assets\/cinematic\.js\?v=20260925-cinematic-v45'\)/);
assert.match(cinematicLoader, /cinematic-fallback/);
assert.doesNotMatch(cinematicLoader, /fetch\(/);
assert.doesNotMatch(cinematicLoader, /innerHTML\s*=/);

assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/);
assert.match(styles, /\.cinematic-fallback/);
assert.doesNotMatch(styles, /backdrop-filter/);

console.log('Cinematic navigation regression test passed.');
