const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const contract = require('./fixtures/html-cleanup-contract.json');
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const css = fs.readFileSync(path.join(root, 'assets/styles/portal.css'), 'utf8');
const sources = contract.files.map(file => fs.readFileSync(path.join(root, 'assets/styles/source', file), 'utf8')).join('');
assert.equal(css, sources, 'The deployed stylesheet must match the ordered maintainable sources');
assert.equal(crypto.createHash('sha256').update(css).digest('hex'), contract.cssSha256, 'Extraction preserves every style and override, normalizing only relative image URLs');
assert.deepEqual([...html.matchAll(/\bid="([^"]+)"/g)].map(m => m[1]), contract.ids, 'All real workspace IDs and their order survive');
assert.deepEqual([...html.matchAll(/\bon(?:click|submit|change|input|keydown|keyup|focus|blur)="([^"]+)"/g)].map(m => m[0]), contract.handlers, 'All markup handlers survive unchanged');
assert.ok(!html.includes('<style>'), 'Bulk styles belong outside the HTML');
assert.ok(html.indexOf('/assets/cinematic.css') < html.indexOf('/assets/styles/portal.css'));
assert.ok(html.indexOf('/assets/styles/portal.css') < html.indexOf('/assets/ambient-background.css'));
assert.match(html, /id="littleFeetAntarcticAudio" preload="none"/);
assert.equal((html.match(/data-src="\/assets\/video\/little-feet-login-clean.mp4"/g) || []).length, 2);
console.log(`HTML cleanup contract passed: ${contract.ids.length} IDs, ${contract.handlers.length} handlers, exact CSS cascade and deferred media.`);
