const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const {spawn} = require('node:child_process');
const root=path.resolve(__dirname,'..'), tempRoot=path.join(root,'tmp');
fs.mkdirSync(tempRoot,{recursive:true});const temp=fs.mkdtempSync(path.join(tempRoot,'role-lifecycle-'));
for(const file of fs.readdirSync(root).filter(x=>x.endsWith('.js')))fs.copyFileSync(path.join(root,file),path.join(temp,file));
fs.cpSync(path.join(root,'lib'),path.join(temp,'lib'),{recursive:true});
const roles=['parent','teacher','principal','district','admin','school_accounts','staff','crm','accounts','support'];
const pin='RoleLifecyclePass1', pinHash=crypto.scryptSync(pin,'little-feet-pin-salt',64).toString('hex');
const company=new Set(['staff','crm','accounts','support']);
const makeUser=(username,role,extra={})=>({username,name:username,role,pinHash,verificationStatus:'Active',schoolId:company.has(role)?'':'alpha',schoolName:company.has(role)?'':'Alpha School',assignedClasses:role==='teacher'?['Grade R']:[],...extra});
fs.writeFileSync(path.join(temp,'littlefeet-replica.json'),JSON.stringify({
 schools:[{id:'alpha',name:'Alpha School',status:'active'},{id:'bravo',name:'Bravo School',status:'active'}],
 users:[...roles.map(role=>makeUser('role-'+role,role,role==='staff'?{platformAccess:true,schoolId:'alpha',schoolName:'Alpha School'}:role==='parent'?{linkedLearners:['Alice'],requestedLearnerLinks:['Bob'],parentRelationshipStatus:'Pending administrator approval'}:{})),makeUser('owner@example.test','admin',{platformAccess:true}),makeUser('other-company-admin','admin',{platformAccess:true,schoolId:'bravo',schoolName:'Bravo School'}),makeUser('role-bravo-admin','admin',{schoolId:'bravo',schoolName:'Bravo School'}),makeUser('mutation-teacher','teacher'),makeUser('pending-case-teacher','teacher',{verificationStatus:'SCHOOL VERIFICATION PENDING'}),makeUser('rename-employee','teacher'),makeUser('rename-parent','parent',{linkedLearners:['Alice'],parentRelationshipStatus:'Administrator approved'})],
 students:[{id:'alice',studentName:'Alice',className:'Grade R',schoolId:'alpha',schoolName:'Alpha School'},{id:'bob',studentName:'Bob',className:'Grade 1',schoolId:'alpha',schoolName:'Alpha School'}],subjectMarks:[{id:'bob-mark',learnerName:'Bob',learnerKey:'bob',className:'Grade 1',schoolId:'alpha',schoolName:'Alpha School',subject:'Maths',term:'Term 4',year:2026,percentage:84}],worksheets:[{id:'bob-work',studentName:'Bob',className:'Grade 1',schoolId:'alpha',grade:84,title:'Restricted Grade 1 result'}],consentRecords:[{id:'bob-consent',schoolId:'alpha',learnerName:'Bob',guardianName:'Bob guardian',marketingPhotos:false}],staffTasks:[{id:'rename-task',title:'Carry-over employee task',assignedTo:'rename-employee',createdBy:'role-admin',status:'Open',schoolId:'alpha'}],staffQualifications:[{id:'rename-qualification',username:'rename-employee',name:'Employee certificate',schoolId:'alpha'}],directMessages:[{id:'rename-message',sender:'rename-employee',recipient:'role-principal',message:'Employee conversation',schoolId:'alpha'}],parentPayments:[{id:'rename-charge',parentUsername:'rename-parent',description:'Existing family charge',amount:50,paymentStatus:'unpaid',schoolId:'alpha'}],schoolBilling:{alpha:{orders:[{reference:'LF-COMPANY-INVOICE',monthlyTotal:120,paymentStatus:'awaiting_payment',planCode:'ecd'}]}},moduleRecords:{},tickets:[{id:'protected-school-delete',category:'School deletion request',schoolId:'alpha',status:'Open',createdBy:'role-principal'},{id:'rename-ticket',subject:'Employee request',assignedTo:'rename-employee',createdBy:'role-admin',status:'Open',schoolId:'alpha'}],registry:[]
}));
const port=20900+Math.floor(Math.random()*200),base='http://127.0.0.1:'+port;
let child,stderr='';
const start=async()=>{child=spawn(process.execPath,['server.js'],{cwd:temp,env:{...process.env,NODE_ENV:'test',PORT:String(port),LF_OWNER_ADMIN_USERNAME:'owner@example.test',SESSION_SECRET:'role-lifecycle-session',LF_FIELD_ENCRYPTION_KEY:'role-lifecycle-fields'},stdio:['ignore','ignore','pipe']});child.stderr.on('data',x=>{stderr+=x;});for(let i=0;i<150;i++){if(child.exitCode!==null)throw Error(stderr);try{if((await fetch(base+'/api/health')).ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Role lifecycle server failed: '+stderr);};
const stop=()=>new Promise(resolve=>{if(!child||child.exitCode!==null)return resolve();child.once('exit',resolve);child.kill();});
const request=async(route,cookie,method='GET',body)=>{const response=await fetch(base+route,{method,headers:{...(cookie?{cookie}:{}),...(body===undefined?{}:{'content-type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body)});const text=await response.text();let data;try{data=JSON.parse(text);}catch{data=text;}return {status:response.status,data,cookie:response.headers.get('set-cookie')?.split(';')[0]||cookie};};
const login=async username=>{const r=await request('/api/login',null,'POST',{username,pin});assert.equal(r.status,200);return r.cookie;};
const failures=[];const check=(label,actual,expected)=>{console.log(label+': '+JSON.stringify(actual)+' (expected '+JSON.stringify(expected)+')');try{assert.deepEqual(actual,expected);}catch{failures.push(label);}};
(async()=>{try{
 await start();const cookies={};for(const role of roles)cookies[role]=await login('role-'+role);let owner=await login('owner@example.test');
 check('Legacy employee platform flag is ineffective',(await request('/api/auth/session',cookies.staff)).data.account?.platformAccess ?? (await request('/api/auth/session',cookies.staff)).data.user?.platformAccess,false);
 check('Pending verification blocks password sign-in regardless of case',(await request('/api/login',null,'POST',{username:'pending-case-teacher',pin})).status,403);
 check('Authorised owner can approve a pending employee',(await request('/api/accounts/pending-case-teacher/approve',owner,'POST',{})).status,200);
 check('Approved employee can sign in',(await request('/api/login',null,'POST',{username:'pending-case-teacher',pin})).status,200);
 for(const role of roles){
  const management=['admin','crm'].includes(role);
  check(role+' account-management boundary',(await request('/api/accounts',cookies[role])).status,management?200:403);
  const finance=['parent','principal','admin','school_accounts'].includes(role);
  check(role+' finance boundary',(await request('/api/parent-payments',cookies[role])).status,finance?200:403);
  const learners=['teacher','principal','admin'].includes(role);
  const learning=['parent','teacher','principal','admin'].includes(role);
  for(const route of ['/api/academics/marks','/api/academics/report-cards','/api/discipline','/api/grade-r/assessments','/api/elda/assessments'])check(role+' learning boundary '+route,(await request(route,cookies[role])).status,learning?200:403);
  for(const route of ['/api/consents','/api/pickups'])check(role+' child-safety boundary '+route,(await request(route,cookies[role])).status,learners?200:403);
  check(role+' private registry boundary',(await request('/api/registry',cookies[role])).status,learners?200:403);
 }
 for(const role of ['staff','crm','accounts','support']) {
  for(const route of ['/api/accounts','/api/schools/search?q=Alpha','/api/parent-contacts','/api/finance/overview','/api/system-logs','/api/students/search?q=Alice'])check(role+' owner or child tool boundary '+route,(await request(route,cookies[role])).status,role==='crm'&&['/api/accounts','/api/schools/search?q=Alpha'].includes(route)?200:403);
  check(role+' company client job boundary',(await request('/api/company/clients',cookies[role])).status,role==='crm'?200:403);
  check(role+' company billing job boundary',(await request('/api/company/billing',cookies[role])).status,role==='accounts'?200:403);
  check(role+' keeps own staff work',(await request('/api/staff/tasks',cookies[role])).status,200);
 }
 check('Sales client notes save',(await request('/api/company/clients/alpha',cookies.crm,'PUT',{note:'Follow up on requested school demonstration'})).status,200);
 check('Sales client notes contain no child data',(await request('/api/company/clients',cookies.crm)).data.some(x=>'students' in x||'users' in x),false);
 check('Accounts can reconcile a real company invoice',(await request('/api/company/billing/reconcile',cookies.accounts,'POST',{reference:'LF-COMPANY-INVOICE',amount:120,eventId:'bank-one',bankReference:'BANK-ONE'})).status,201);
 check('Duplicate company bank event is idempotent',(await request('/api/company/billing/reconcile',cookies.accounts,'POST',{reference:'LF-COMPANY-INVOICE',amount:120,eventId:'bank-one',bankReference:'BANK-ONE'})).status,200);
 check('Company support can message a school principal',(await request('/api/chat/direct',cookies.support,'POST',{recipient:'role-principal',message:'School service conversation'})).status,200);
 check('School principal can read company service conversation',(await request('/api/chat/direct/role-principal/role-support',cookies.principal)).data.some(x=>x.message==='School service conversation'),true);
 check('School principal can reply to company support',(await request('/api/chat/direct',cookies.principal,'POST',{recipient:'role-support',message:'School service reply'})).status,200);
 check('Another school cannot eavesdrop on company chat',(await request('/api/chat/direct/role-principal/role-support',await login('role-bravo-admin'))).status,403);
 check('Sales cannot read unrelated service tickets',(await request('/api/tickets',cookies.crm)).data.some(x=>x.id==='rename-ticket'),false);
 check('Sales cannot update unrelated service tickets',(await request('/api/tickets/update',cookies.crm,'POST',{id:'rename-ticket',status:'Completed'})).status,404);
 check('Invalid support status update rejected',(await request('/api/tickets/update',cookies.support,'POST',{id:'rename-ticket',assignedTo:'role-crm',status:'Invalid'})).status,400);
 check('Rejected ticket update preserves previous assignee',(await request('/api/tickets',cookies.support)).data.find(x=>x.id==='rename-ticket').assignedTo,'rename-employee');
 const crmList=await request('/api/accounts',cookies.crm);
 check('CRM user list excludes all company accounts and the owner',crmList.data.some(x=>company.has(x.role)||x.platformAccess||x.username==='owner@example.test'),false);
 const crmSchools=await request('/api/schools/search?q=School',cookies.crm);
 check('CRM can select registered client schools',crmSchools.data.results.some(x=>x.schoolId==='bravo'),true);
 for(const role of ['teacher','parent','principal','district','school_accounts','admin']) {
  const created=await request('/api/accounts',cookies.crm,'POST',{username:'crm-created-'+role,name:'Client '+role,role,pin,schoolName:'Alpha School',assignedClasses:role==='teacher'?['Grade R']:[],linkedLearners:role==='parent'?['Alice']:[],platformAccess:true});
  check('CRM creates school '+role,created.status,201);
  check('CRM-created '+role+' cannot gain platform access',created.data.account?.platformAccess,false);
  check('CRM-created '+role+' has a working login',(await request('/api/login',null,'POST',{username:'crm-created-'+role,pin})).status,200);
 }
 check('CRM can add a user for a different client school',(await request('/api/accounts',cookies.crm,'POST',{username:'crm-bravo-teacher',name:'Bravo teacher',role:'teacher',pin,schoolName:'Bravo School'})).status,201);
 check('CRM can edit a client user',(await request('/api/accounts/crm-bravo-teacher',cookies.crm,'PUT',{name:'Updated Bravo teacher'})).status,200);
 check('CRM can reset a client login wait',(await request('/api/accounts/crm-bravo-teacher/reset-login-lockout',cookies.crm,'POST',{})).status,200);
 check('CRM can approve an existing client account',(await request('/api/accounts/crm-bravo-teacher/approve',cookies.crm,'POST',{})).status,200);
 check('CRM cannot transfer an existing user to another client',(await request('/api/accounts/crm-bravo-teacher',cookies.crm,'PUT',{schoolName:'Alpha School'})).status,403);
 check('CRM cannot grant company roles',(await request('/api/accounts/crm-bravo-teacher',cookies.crm,'PUT',{role:'crm',schoolName:''})).status,403);
 check('CRM cannot create company employees',(await request('/api/accounts',cookies.crm,'POST',{username:'crm-company-escalation',name:'Blocked employee',role:'staff',pin})).status,403);
 check('CRM cannot create a new school through a user form',(await request('/api/accounts',cookies.crm,'POST',{username:'crm-unknown-school',name:'Blocked school',role:'teacher',pin,schoolName:'Unregistered client'})).status,403);
 check('Rejected CRM school creation leaves no school row',(await request('/api/company/clients',cookies.crm)).data.some(x=>x.name==='Unregistered client'),false);
 check('CRM learner picker returns only the selected school',(await request('/api/accounts/learner-options?schoolName=Alpha%20School',cookies.crm)).data.every(x=>['Alice','Bob'].includes(x.studentName)&&!('medicalNotes' in x)),true);
 check('School administrator cannot use CRM picker to read another school',(await request('/api/accounts/learner-options?schoolName=Bravo%20School',cookies.admin)).status,404);
 check('CRM cannot link a parent to a different school learner',(await request('/api/accounts',cookies.crm,'POST',{username:'crm-bad-parent',name:'Blocked parent',role:'parent',pin,schoolName:'Bravo School',linkedLearners:['Alice']})).status,400);
 check('CRM cannot change the owner password',(await request('/api/accounts/owner%40example.test',cookies.crm,'PUT',{pin:'AttackerPass1'})).status,404);
 check('CRM cannot delete the owner',(await request('/api/accounts/owner%40example.test',cookies.crm,'DELETE')).status,404);
 check('CRM cannot edit another company administrator',(await request('/api/accounts/other-company-admin',cookies.crm,'PUT',{name:'Blocked admin edit'})).status,404);
 check('CRM cannot delete entire schools',(await request('/api/school-deletion/execute',cookies.crm,'POST',{ticketId:'protected-school-delete',confirmation:'DELETE SCHOOL'})).status,403);
 check('CRM can delete a client user',(await request('/api/accounts/crm-bravo-teacher',cookies.crm,'DELETE')).status,200);
 check('Deleted client user cannot sign in',(await request('/api/login',null,'POST',{username:'crm-bravo-teacher',pin})).status,401);
 check('Teacher cannot read marks from an unassigned class',(await request('/api/academics/marks',cookies.teacher)).data.marks?.some(x=>x.learnerName==='Bob'),false);
 check('Teacher cannot submit marks for an unassigned class',(await request('/api/academics/marks',cookies.teacher,'POST',{learnerName:'Bob',subject:'Maths',assessmentName:'Unauthorised',term:'Term 4',year:2026,score:9,maximum:10})).status,404);
 check('Teacher cannot edit an unassigned class mark by ID',(await request('/api/academics/marks/bob-mark',cookies.teacher,'PATCH',{score:9})).status,404);
 check('Teacher can still submit marks for an assigned learner',(await request('/api/academics/marks',cookies.teacher,'POST',{learnerName:'Alice',subject:'Maths',assessmentName:'Authorised',term:'Term 4',year:2026,score:8,maximum:10})).status,201);
 check('Teacher cannot read another class analytics',(await request('/api/analytics/Bob',cookies.teacher)).status,404);
 check('School finance cannot read learner growth analytics',(await request('/api/analytics/Bob',cookies.school_accounts)).status,403);
 check('Teacher cannot read another class consent',(await request('/api/consents',cookies.teacher)).data.some(x=>x.learnerName==='Bob'),false);
 check('Teacher cannot change another class consent',(await request('/api/consents',cookies.teacher,'POST',{learnerName:'Bob',guardianName:'Bob guardian',marketingPhotos:true})).status,403);
 check('Teacher can capture assigned learner consent',(await request('/api/consents',cookies.teacher,'POST',{learnerName:'Alice',guardianName:'Alice guardian',marketingPhotos:false})).status,201);
 for(const role of ['staff','crm','accounts'])check(role+' can create real company work tasks',(await request('/api/staff/tasks',cookies[role],'POST',{title:'Company work for '+role})).status,201);
 const officeTask=await request('/api/staff/tasks',owner,'POST',{title:'Company sales work',assignedTo:'role-crm'});
 check('Owner can assign work to company employees',officeTask.status,201);
 check('Company employee work stays outside school records',officeTask.data.item?.schoolId,'');
 const principalDirectory=await request('/api/staff/directory',cookies.principal);
 check('Principal has a functioning staff directory',Array.isArray(principalDirectory.data),true);
 if(Array.isArray(principalDirectory.data))check('Principal directory excludes company accounts',principalDirectory.data.some(x=>company.has(x.role)||x.username==='owner@example.test'),false);
 const otherAdmin=await login('other-company-admin');
 check('Another company administrator cannot change the owner',(await request('/api/accounts/owner%40example.test',otherAdmin,'PUT',{name:'Changed boss'})).status,404);
 check('Another company administrator cannot delete the owner',(await request('/api/accounts/owner%40example.test',otherAdmin,'DELETE')).status,404);
 check('Even the owner cannot delete the protected owner account',(await request('/api/accounts/owner%40example.test',owner,'DELETE')).status,400);
 check('School deletion cannot remove the owner indirectly',(await request('/api/school-deletion/execute',cookies.admin,'POST',{ticketId:'protected-school-delete',confirmation:'DELETE SCHOOL'})).status,409);
 check('Protected owner retains original name after rejected edits',(await request('/api/accounts',owner)).data.find(x=>x.username==='owner@example.test').name,'owner@example.test');
 check('School admin cannot edit company owner',(await request('/api/accounts/owner%40example.test',cookies.admin,'PUT',{name:'Wrong owner edit'})).status,404);
 for(const role of ['staff','crm','accounts'])check(role+' cannot alter protected company owner',(await request('/api/accounts/owner%40example.test',cookies[role],'PUT',{name:'Employee changes boss'})).status,role==='crm'?404:403);
 check('Company owner absent from school account-management list',(await request('/api/accounts',cookies.admin)).data.some(x=>x.username==='owner@example.test'),false);
 check('School admin cannot create company staff',(await request('/api/accounts',cookies.admin,'POST',{username:'blocked-company',name:'Blocked company',role:'support',pin})).status,403);
 const hired=await request('/api/accounts',owner,'POST',{username:'new-support@example.test',name:'New support employee',role:'support',pin});
 check('Company owner can create unlinked support account',hired.status,201);check('Company support requires no fake school',hired.data.account?.schoolId,'');
 check('New company support can sign in',(await request('/api/login',null,'POST',{username:'new-support@example.test',pin})).status,200);
 await request('/api/accounts/role-teacher',owner,'PUT',{name:'Teacher renamed display name'});
 check('Name-only teacher edit preserves assigned classes',(await request('/api/accounts',owner)).data.find(x=>x.username==='role-teacher').assignedClasses,['Grade R']);
 await request('/api/accounts/role-parent',owner,'PUT',{name:'Parent renamed display name'});
 const parent=(await request('/api/accounts',owner)).data.find(x=>x.username==='role-parent');
 check('Name-only parent edit preserves linked learners',parent.linkedLearners,['Alice']);check('Name-only parent edit preserves pending requests',parent.requestedLearnerLinks,['Bob']);
 const invalid=await request('/api/accounts/mutation-teacher',owner,'PUT',{role:'crm',schoolName:'',name:'Rejected new name',schoolStoreUrl:'http://invalid.test'});
 check('Invalid role update rejected',invalid.status,400);
 check('Rejected update cannot grant company access',(await request('/api/accounts',owner)).data.find(x=>x.username==='mutation-teacher').role,'teacher');
 check('Rejected update keeps original name',(await request('/api/accounts',owner)).data.find(x=>x.username==='mutation-teacher').name,'mutation-teacher');
 const shortPin=await request('/api/accounts/role-district',owner,'PUT',{username:'incorrectly-renamed',pin:'x'});
 check('Invalid password update rejected',shortPin.status,400);check('Rejected password cannot rename account',(await request('/api/accounts',owner)).data.some(x=>x.username==='role-district'),true);
 const supportPicker=await request('/api/tickets/assignees',cookies.support);check('Support has a working ticket assignee directory',Array.isArray(supportPicker.data),true);
 if(Array.isArray(supportPicker.data)){check('Company employees appear in ticket assignment',supportPicker.data.filter(x=>company.has(x.role)).length>=4,true);check('Assignee directory omits password hashes',supportPicker.data.some(x=>'pinHash' in x||'mailboxConnection' in x),false);}
 const schoolPicker=await request('/api/tickets/assignees',cookies.admin);check('School ticket assignees stay in own school',Array.isArray(schoolPicker.data)&&schoolPicker.data.every(x=>x.schoolId==='alpha'&&!company.has(x.role)&&x.username!=='owner@example.test'),true);
 check('Support cannot turn directory access into account management',(await request('/api/accounts',cookies.support)).status,403);
 check('Valid employee username change succeeds',(await request('/api/accounts/rename-employee',owner,'PUT',{username:'renamed-employee'})).status,200);
 const renamed=await login('renamed-employee');
 check('Renamed employee retains assigned work',(await request('/api/staff/tasks',renamed)).data.some(x=>x.id==='rename-task'),true);
 check('Renamed employee retains certificates',(await request('/api/staff/qualifications',renamed)).data.some(x=>x.id==='rename-qualification'),true);
 check('Renamed employee retains assigned tickets',(await request('/api/tickets',renamed)).data.some(x=>x.id==='rename-ticket'),true);
 check('Renamed employee retains private conversations',(await request('/api/chat/direct/renamed-employee/role-principal',renamed)).data.some(x=>x.id==='rename-message'),true);
 await request('/api/accounts/rename-parent',owner,'PUT',{username:'renamed-parent'});
 const renamedParent=await login('renamed-parent');
 check('Renamed parent retains their payment records',(await request('/api/parent-payments',renamedParent)).data.payments.some(x=>x.id==='rename-charge'),true);
 check('Configured owner identity cannot be renamed',(await request('/api/accounts/owner%40example.test',owner,'PUT',{username:'renamed-owner@example.test'})).status,400);
 await request('/api/term',cookies.admin,'POST',{term:'Term 4'});await stop();await start();owner=await login('owner@example.test');
 check('CRM-created school user persists and signs in after restart',(await request('/api/login',null,'POST',{username:'crm-created-teacher',pin})).status,200);
 check('Sales notes survive restart',(await request('/api/company/clients',await login('role-crm'))).data.find(x=>x.id==='alpha')?.note,'Follow up on requested school demonstration');
 check('Company work remains outside school records after restart',(await request('/api/staff/tasks',owner)).data.find(x=>x.id===officeTask.data.item.id)?.schoolId,'');
 check('Company employee persists and signs in after restart',(await request('/api/login',null,'POST',{username:'new-support@example.test',pin})).status,200);
 check('Rejected privilege update remains unchanged after restart',(await request('/api/accounts',owner)).data.find(x=>x.username==='mutation-teacher').role,'teacher');
 assert.deepEqual(failures,[],'Role/account failures: '+failures.join(', '));console.log('All ten role boundaries and real account lifecycle checks passed.');
}finally{await stop();const relative=path.relative(tempRoot,path.resolve(temp));assert.ok(relative&&!relative.startsWith('..')&&!path.isAbsolute(relative));fs.rmSync(temp,{recursive:true,force:true,maxRetries:10,retryDelay:100});}})().catch(e=>{console.error(e);process.exitCode=1;});
