const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const page = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const server = fs.readFileSync(path.join(root, 'server.js'), 'utf8');
const client = fs.readFileSync(path.join(root, 'backup.js'), 'utf8');
const robots = fs.readFileSync(path.join(root, 'robots.txt'), 'utf8');
const sitemap = fs.readFileSync(path.join(root, 'sitemap.xml'), 'utf8');
const checklist = fs.readFileSync(path.join(root, 'VIDEO_REVIEW_CHECKLIST.md'), 'utf8');
const manifest = fs.readFileSync(path.join(root, 'manifest.webmanifest'), 'utf8');
const serviceWorker = fs.readFileSync(path.join(root, 'service-worker.js'), 'utf8');
const mobilePwa = fs.readFileSync(path.join(root, 'assets', 'mobile-pwa.js'), 'utf8');
const myDay = fs.readFileSync(path.join(root, 'assets', 'my-day.js'), 'utf8');
const workplaceExtended = fs.readFileSync(path.join(root, 'assets', 'workplace-extended.js'), 'utf8');
const envExample = fs.readFileSync(path.join(root, '.env.example'), 'utf8');
const curriculum = fs.readFileSync(path.join(root, 'assets', 'curriculum-frameworks.js'), 'utf8');
const auroraWallpaper = fs.readFileSync(path.join(root, 'assets', '4k', 'little-feet-aurora-stars-4k.svg'), 'utf8');
const starGlowMask = fs.readFileSync(path.join(root, 'assets', '4k', 'little-feet-star-glow-mask-4k.svg'), 'utf8');

assert.match(page, /<meta name="description" content="Little Feet by Little Feet Technologies \(Pty\) Ltd is a South African school operations platform/);
assert.match(page, /<meta name="robots" content="index,follow,max-image-preview:large">/);
assert.ok(page.includes('<link rel="canonical" href="https://littlefeet.co.za/">'));
assert.ok(page.includes('<script type="application/ld+json">'));
assert.equal((page.match(/<h1\b/gi) || []).length, 1, 'The public document should expose one primary H1.');
assert.match(page, /<h1 role="button" tabindex="0"/);
assert.match(page, /rel="manifest" href="\/manifest\.webmanifest"/);
assert.match(page, /name="theme-color" content="#0d9488"/);
assert.match(page, /id="pwaInstallButton"/);
assert.match(page, /id="accountEditSelect" onchange="selectAccountForEditing\(this\.value\)"/);
assert.match(page, /<option value="staff">Little Feet Staff<\/option>/);
assert.match(page, /<option value="crm">CRM<\/option>/);
assert.match(page, /<option value="school_accounts">School Accounts<\/option>/);
assert.match(page, /<option value="accounts">Little Feet Accounts<\/option>/);
assert.match(page, /<option value="support">Software Support<\/option>/);
assert.match(page, /backup\.js\?v=20260930-accounts-full-v1/);
assert.match(page, /id="accountResetLoginWaitButton"/);
assert.match(page, /Reset 10-minute login wait/);
assert.match(client, /async function resetSelectedAccountLoginWait\(\)/);
assert.match(client, /accountsTab: \[loadAccounts\]/);
assert.match(page, /id="accountSchoolSearch"/);
assert.match(page, /Find school by name/);
assert.match(page, /id="accountSchoolSearchResults"/);
assert.match(client, /function queueAccountSchoolSearch\(force = false\)/);
assert.match(client, /async function searchAccountSchools\(query, token\)/);
assert.match(client, /function selectAccountSchool\(encodedName\)/);
assert.match(client, /\/api\/schools\/search\?q=/);
assert.match(server, /app\.get\('\/api\/schools\/search'/);
assert.match(server, /countrycodes: 'za'/);
assert.match(server, /source: 'OpenStreetMap'/);
assert.doesNotMatch(client, /registryTab: \[loadRegistry, loadAccounts, loadLearnerAccessCodes\]/);
assert.match(client, /if \(!response\.ok\) throw new Error\(accounts\?\.message \|\| 'Unable to load account records\.'\)/);
assert.match(client, /reset-login-lockout/);
assert.match(server, /const clearLoginLockoutForAccount = account =>/);
assert.match(server, /app\.post\('\/api\/accounts\/:username\/reset-login-lockout'/);
assert.match(page, /my-day\.js\?v=20260930-user-switch-v2/);
assert.match(page, /data-my-day-nav="true"/);
assert.match(page, /onclick="switchTab\('myDayTab', this\)"/);
assert.match(page, /id="myDayTab" class="tab-content" data-roles="teacher,principal,admin,staff"/);
assert.match(page, /workplace-extended\.js\?v=20260930-mailbox-providers-v5/);
assert.match(workplaceExtended, /Delivery provider:/);
assert.match(workplaceExtended, /Connect your personal mailbox/);
assert.match(workplaceExtended, /Connect Gmail/);
assert.match(workplaceExtended, /Connect Outlook \/ Microsoft 365/);
assert.match(workplaceExtended, /Connect Zoho Mail/);
assert.match(workplaceExtended, /Connect Yahoo Mail/);
assert.match(workplaceExtended, /setup required/);
assert.match(server, /zoho: Boolean\(process\.env\.ZOHO_CLIENT_ID && process\.env\.ZOHO_CLIENT_SECRET\)/);
assert.match(server, /yahoo: Boolean\(process\.env\.YAHOO_CLIENT_ID && process\.env\.YAHOO_CLIENT_SECRET\)/);
assert.doesNotMatch(server, /mailboxOauthFlag/);

assert.match(workplaceExtended, /Connect Gmail/);
assert.match(workplaceExtended, /Connect Outlook \/ Microsoft 365/);
assert.match(workplaceExtended, /Connect Zoho Mail/);
assert.match(workplaceExtended, /Connect Yahoo Mail/);
assert.match(workplaceExtended, /href="\/auth\/email\/zoho"/);
assert.match(workplaceExtended, /href="\/auth\/email\/yahoo"/);
assert.doesNotMatch(workplaceExtended, /app-password/i);
assert.doesNotMatch(workplaceExtended, /imapMailboxConnectForm/);
assert.doesNotMatch(workplaceExtended, /name="imapHost"/);
assert.match(workplaceExtended, /\/api\/email\/mailbox\/sync/);
assert.match(server, /GOOGLE_MAILBOX_SCOPE/);
assert.match(server, /const GOOGLE_MAILBOX_CALLBACK_URL = 'https:\/\/littlefeet\.co\.za\/auth\/google\/callback'/);
assert.match(server, /const MICROSOFT_MAILBOX_CALLBACK_URL = 'https:\/\/littlefeet\.co\.za\/auth\/microsoft\/callback'/);
assert.match(server, /google: Boolean\(process\.env\.GOOGLE_CLIENT_ID && process\.env\.GOOGLE_CLIENT_SECRET\)/);
assert.match(server, /microsoft: Boolean\(process\.env\.MICROSOFT_CLIENT_ID && process\.env\.MICROSOFT_CLIENT_SECRET\)/);
assert.match(server, /req\.query\.state === req\.session\.mailboxGoogleOAuthState/);
assert.match(server, /req\.query\.state === req\.session\.mailboxMicrosoftOAuthState/);
assert.match(server, /MICROSOFT_MAILBOX_SCOPE/);
assert.match(server, /app\.get\('\/auth\/email\/google'/);
assert.match(server, /app\.get\('\/auth\/email\/microsoft'/);
assert.match(server, /app\.get\('\/auth\/email\/zoho'/);
assert.match(server, /app\.get\('\/auth\/email\/yahoo'/);
assert.match(server, /ZOHO_MAILBOX_SCOPE/);
assert.match(server, /YAHOO_MAILBOX_SCOPE/);
assert.doesNotMatch(server, /app\.post\('\/api\/email\/mailbox\/imap\/connect'/);
assert.doesNotMatch(server, /connectImapMailboxForActor/);
assert.doesNotMatch(server, /MAILBOX_IMAP_PROVIDERS/);
assert.doesNotMatch(server, /app\.get\('\/auth\/email\/google\/callback'/);
assert.doesNotMatch(server, /app\.get\('\/auth\/email\/microsoft\/callback'/);
assert.match(server, /mailboxConnection, \.\.\.account/);
assert.match(server, /const smtpEmailConfigured = \(\) =>/);
assert.match(server, /host\.includes\('zoho'\) \? 'Zoho SMTP' : 'SMTP'/);
assert.match(server, /tls\.connect\(/);
assert.match(server, /const emailActor = req => getSessionAccount\(req\)/);
assert.match(page, /data-roles="parent,teacher,principal,district,admin,staff,crm,accounts,school_accounts,support"[^>]*><button[^>]*switchTab\('emailIntegrationTab'/);
assert.match(page, /id="emailIntegrationTab" class="tab-content" data-roles="parent,teacher,principal,district,admin,staff,crm,accounts,school_accounts,support"/);
assert.match(page, /class="card role-admin school-setup-card"/);
assert.match(page, /class="workspace-grid school-setup-grid"/);
assert.match(page, /class="guide-link-card school-setup-step"/);
assert.match(page, /class="school-setup-number">1<\/span>Import learners/);
assert.match(page, /\.school-setup-grid \{ grid-template-columns:repeat\(4,minmax\(0,1fr\)\)/);
assert.match(page, /\.school-setup-step \{[\s\S]*min-height:0;/);
assert.match(envExample, /LF_SMTP_HOST=smtp\.zoho\.com/);
assert.match(envExample, /LF_SMTP_PORT=465/);
assert.match(envExample, /LF_SMTP_USERNAME=/);
assert.match(envExample, /LF_SMTP_PASSWORD=/);
assert.match(myDay, /document\.addEventListener\('littlefeet:session-ready', start\)/);
assert.match(myDay, /new MutationObserver\(queueRepair\)/);
assert.match(myDay, /window\.addEventListener\('pageshow', start\)/);
assert.match(myDay, /visibilitychange/);
assert.match(myDay, /tab\?\.dataset\.myDayReady === 'true'/);
assert.match(myDay, /tab\.dataset\.myDayUser = userKey/);
assert.match(myDay, /tab\.dataset\.myDayUser !== userKey/);
assert.match(myDay, /teacher', 'principal', 'admin', 'staff/);
assert.match(client, /function updateAccountRoleFields\(\)/);
assert.match(client, /CEO \/ ADMINISTRATOR/);
assert.match(server, /const PLATFORM_INTERNAL_ROLES = new Set\(\['staff', 'crm', 'accounts', 'support'\]\)/);
assert.match(server, /platformAccess: FULL_PLATFORM_ROLES\.has\(role\)/);
assert.match(client, /function selectAccountForEditing\(encodedUsername\)/);
assert.match(client, /document\.getElementById\('accountEditSelect'\)/);
assert.match(server, /app\.put\('\/api\/accounts\/:username'/);
assert.match(page, /curriculumObservationForm/);
assert.match(page, /class="login-card-tools"/);
assert.match(page, /id="loginLanguagePreference"/);
assert.match(page, /data-lf-i18n="securePortal"/);
assert.match(page, /data-lf-i18n="rememberEmail"/);
assert.match(page, /data-lf-i18n="loginHelp"/);
assert.match(page, /data-lf-i18n="createAccount"/);
assert.match(page, /class="action-btn btn-blue login-audio-compact"/);
assert.match(page, /--lf-bioluminescent-teal:#00B4D8/);
assert.match(page, /--panel-bg:#1B4965/);
assert.match(page, /body:not\(\.light-mode\)[\s\S]*--primary-color:#0D0D1D/);
assert.match(page, /body:not\(\.light-mode\)[\s\S]*--panel-bg:#0D0D1D/);
assert.match(page, /linear-gradient\(180deg, #1A1A2D, #0D0D1D\)/);
assert.match(page, /body:not\(\.light-mode\) \.app-sidebar[\s\S]*rgba\(17,17,33,\.96\)[\s\S]*rgba\(8,8,18,\.97\)/);
assert.match(page, /body:not\(\.light-mode\) \.portal-welcome-banner[\s\S]*rgba\(13,13,29,\.985\)[\s\S]*admin-mascot-dashboard-4k\.jpg/);
assert.match(page, /body\.light-mode[\s\S]*--bg-dark:#163E56/);
assert.match(page, /linear-gradient\(145deg, rgba\(27,73,101,\.93\), rgba\(18,56,80,\.88\)\)/);
assert.match(page, /body\.light-mode input,[\s\S]*color:#F7FBFF !important/);
assert.match(page, /body\.light-mode[\s\S]*--primary-color:#00B4D8/);
assert.match(page, /body\.light-mode \.guide-open,[\s\S]*color:#00B4D8 !important/);
assert.match(page, /body\.light-mode input:focus,[\s\S]*border-color:#00B4D8 !important/);
assert.match(page, /\.login-new-account \{[\s\S]*grid-template-columns:max-content minmax\(0,1fr\) !important/);
assert.match(page, /\.login-new-account \.action-btn \{[\s\S]*width:100% !important/);
assert.match(page, /#loginForm #loginUsername:-webkit-autofill/);
assert.match(page, /#loginForm #loginPin:-webkit-autofill/);
assert.match(page, /-webkit-text-fill-color:#f7fbff !important/);
assert.match(page, /0 0 0 1000px #0f304e inset/);
assert.match(page, /body\.light-mode #loginForm #loginUsername:-webkit-autofill/);
assert.match(page, /0 0 0 1000px #abc5cd inset/);
assert.match(page, /id="icon-volume-off"/);
assert.match(page, /data-mute-label="Sound On" data-unmute-label="Muted"/);
assert.match(page, /\.login-audio-compact \.ui-icon \{[\s\S]*width:1\.28rem/);
assert.match(client, /const iconId = portalAudioMuted \? 'icon-volume-off' : 'icon-volume'/);
assert.match(client, /classList\.toggle\('is-muted', portalAudioMuted\)/);
assert.match(page, /class="login-info-runner"/);
assert.match(page, /aria-label="About Little Feet"/);
assert.match(page, /Little Feet<\/strong>[\s\S]*secure ECD, primary and secondary school operations platform/);
assert.match(page, /@keyframes loginInfoRunner/);
assert.match(page, /\.login-info-runner-track \{[\s\S]*animation:loginInfoRunner 30s linear infinite/);
assert.match(page, /@media \(max-width:640px\)[\s\S]*\.login-info-runner-track \{ animation-duration:24s; \}/);
assert.match(page, /@media \(min-width:1600px\)[\s\S]*animation-duration:34s/);
assert.match(page, /@media \(max-width:900px\) and \(max-height:600px\) and \(orientation:landscape\)[\s\S]*\.login-info-runner/);
assert.match(page, /@media \(prefers-reduced-motion: reduce\)[\s\S]*\.login-info-runner-track[\s\S]*animation:none/);
assert.match(page, /onclick="openPopiaPrivacyNotice\(\)"/);
assert.match(page, /onclick="openTermsOfService\(\)"/);
assert.doesNotMatch(page, /class="login-context"/);
assert.doesNotMatch(page, /class="login-trust-row"/);
assert.match(page, /preferences-enhancements\.js\?v=20260925-preferences-v2/);
assert.match(page, /onclick="openPopiaPrivacyNotice\(\)">Privacy &amp; POPIA Notice/);
assert.match(page, /onclick="openTermsOfService\(\)">Terms of Service/);
assert.match(page, /NCF Birth–4/);
assert.match(page, /CAPS Grade R/);

for (const asset of ['xlsx.js', 'qrcode.js', 'leaflet.js', 'leaflet-markercluster.js']) {
  assert.match(page, new RegExp('<script src="\\/vendor\\/' + asset.replace('.', '\\.') + '" defer><\\/script>'));
}

assert.match(page, /id="appModal" class="modal-overlay hidden" role="dialog" aria-modal="true" aria-labelledby="modalTitle"/);
assert.match(page, /class="modal-close"[^>]*aria-label="Close dialog"/);
assert.match(client, /let modalReturnFocus = null/);
assert.match(client, /modal\.querySelector\('\.modal-close'\)\?\.focus\(\)/);
assert.match(client, /event\.key !== 'Escape'/);
assert.match(client, /modalReturnFocus\?\.isConnected/);

assert.match(page, /id="wallpaperImage"[^>]*loading="lazy"[^>]*decoding="async"/);
assert.match(page, /little-feet-aurora-stars-4k\.svg/);
assert.match(page, /@keyframes portalGlowPulse/);
assert.match(page, /little-feet-star-glow-mask-4k\.svg/);
assert.match(page, /#authSection::before[\s\S]*little-feet-aurora-stars-4k\.svg/);
assert.match(page, /#authSection::after[\s\S]*little-feet-star-glow-mask-4k\.svg/);
assert.match(page, /#authSection::after[\s\S]*animation:portalGlowPulse 5\.8s/);
const whiteStarCount = (auroraWallpaper.match(/fill="#ffffff"/g) || []).length;
const trackedCoreCount = (starGlowMask.match(/class="tracked-star-core"/g) || []).length;
const trackedHaloCount = (starGlowMask.match(/class="tracked-star-halo"/g) || []).length;
assert.equal(whiteStarCount, 457, 'The current 4K wallpaper should expose the expected pure-white star count.');
assert.equal(trackedCoreCount, whiteStarCount, 'Every white star must have one pulsating core glow.');
assert.equal(trackedHaloCount, whiteStarCount, 'Every white star must have one matching halo glow.');
assert.match(starGlowMask, /data-tracked-white-stars="457"/);
assert.match(page, /animation:portalGlowPulse 5\.8s/);
assert.match(page, /will-change:opacity/);
assert.doesNotMatch(page, /portal-ribbons/);
assert.doesNotMatch(page, /standby-ribbon/);
assert.doesNotMatch(page, /ribbonDrift/);
assert.doesNotMatch(page, /filter:blur\(34px\)/);
assert.doesNotMatch(page, /animation:portalAuroraDrift/);
assert.doesNotMatch(page, /auroraStrobe/);
assert.match(page, /prefers-reduced-motion: reduce/);
assert.match(page, /body\.portal-active\.light-mode \{ background-color:var\(--bg-dark\); \}/);
assert.match(page, /backup\.js\?v=20260930-accounts-full-v1/);
assert.match(page, /id="stickyNoteForm"/);
assert.doesNotMatch(page, /onsubmit="saveStickyNote\(event\)"/);
assert.match(client, /function bindStickyNoteForm\(\)/);
assert.match(client, /form\.addEventListener\('submit', saveStickyNote\)/);
assert.match(client, /window\.saveStickyNote = saveStickyNote/);
assert.match(client, /function editStickyNote\(id\)/);
assert.match(client, /method: noteId \? 'PATCH' : 'POST'/);
assert.doesNotMatch(page, /little-feet-wallpaper-no-moon-4k\.jpg/);
assert.doesNotMatch(page, /campfire wallpaper/i);
assert.match(client, /classList\.add\('has-custom-wallpaper'\)/);
assert.match(client, /classList\.remove\('has-custom-wallpaper'\)/);
assert.match(client, /northern lights wallpaper is active/);

assert.match(page, /href="#privacy-safeguarding"/);
assert.match(page, /href="#terms-of-service"/);
assert.match(page, /href="#copyright-content"/);
assert.match(page, /Copyright, Trade Marks &amp; IP/);

assert.match(server, /app\.get\('\/manifest\.webmanifest'/);
assert.match(server, /app\.get\('\/service-worker\.js'/);
assert.match(server, /app\.get\('\/robots\.txt'/);
assert.match(server, /app\.get\('\/sitemap\.xml'/);
assert.match(robots, /User-agent: \*/);
assert.match(robots, /Disallow: \/api\//);
assert.ok(robots.includes('Sitemap: https://littlefeet.co.za/sitemap.xml'));
assert.ok(sitemap.includes('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'));
assert.ok(sitemap.includes('<loc>https://littlefeet.co.za/</loc>'));
assert.match(checklist, /Source set reviewed: the 19 videos/);
assert.match(checklist, /Rules applied during this review/);
assert.match(server, /RENDER_GIT_COMMIT/);
assert.match(server, /RENDER_GIT_REPO_SLUG/);
assert.match(server, /cleanReleaseVersion/);
assert.match(server, /version: '1\.0'/);
assert.match(server, /commit\?\.stats\?\.total/);
assert.match(server, /source: 'Render'/);
assert.match(client, /Latest platform improvements/);
assert.doesNotMatch(client, /Render deploy/);
assert.doesNotMatch(client, /update line/);

const parsedManifest = JSON.parse(manifest);
assert.equal(parsedManifest.display, 'standalone');
assert.equal(parsedManifest.scope, '/');
assert.equal(parsedManifest.theme_color, '#0d9488');
assert.match(serviceWorker, /isPrivateRequest/);
assert.match(serviceWorker, /url\.pathname\.startsWith\('\/api\/'\)/);
assert.match(serviceWorker, /event\.request\.mode === 'navigate'/);
assert.match(mobilePwa, /beforeinstallprompt/);
assert.match(mobilePwa, /navigator\.serviceWorker\.register\('\/service-worker\.js'/);
assert.match(curriculum, /ELDA 1 · Well-being/);
assert.match(curriculum, /ELDA 6 · Knowledge and Understanding of the World/);
assert.match(curriculum, /CAPS Grade R/);

assert.match(page, /name="viewport" content="width=device-width, initial-scale=1\.0, viewport-fit=cover"/);
assert.match(page, /Cross-device layout hardening/);
assert.match(page, /@media \(max-width:360px\)/);
assert.match(page, /@media \(max-width:900px\) and \(max-height:600px\) and \(orientation:landscape\)/);
assert.match(page, /\.modal-overlay \{[\s\S]*safe-area-inset-top[\s\S]*safe-area-inset-right/);
assert.match(page, /\.app-sidebar \{[\s\S]*max-width:calc\(100vw/);
assert.match(page, /cinematic\.css\?v=20260926-cinematic-v14/);

assert.match(page, /Little Feet™ School Portal/);
assert.match(page, /Official site: <a href="https:\/\/littlefeet\.co\.za\//);
assert.match(page, /Built for South African ECD, primary and secondary school communities across learning, operations, family engagement, finance, staff work, safeguarding and privacy workflows/);
assert.doesNotMatch(page, /<strong>Portal status:<\/strong>/);
assert.doesNotMatch(page, /Designed to support ECD, education, POPIA and safeguarding workflows/);
assert.match(page, /\.nav-term-panel \{ display:grid; grid-template-columns:minmax\(0,1fr\) auto/);
assert.match(page, /\.nav-term-panel \.nav-term-edit \{ grid-column:2; grid-row:1 \/ span 2/);
assert.match(page, /\.nav-term-status \{ grid-column:1; grid-row:2/);
assert.match(page, /Login readability pass/);
assert.match(page, /\.login-card-tools \{ display:grid; grid-template-columns:minmax\(0,1fr\)/);
assert.match(page, /\.login-secure-label \{[\s\S]*font-size:\.76rem/);
assert.match(page, /\.login-card-actions \{ display:grid; grid-template-columns:minmax\(0,1fr\) 82px/);
assert.match(page, /\.login-audio-compact span \{ position:static/);
assert.match(page, /\.login-utility-row \{ grid-template-columns:minmax\(0,1fr\) minmax\(170px,220px\)/);
assert.match(page, /Copyright, Trade Marks &amp; IP/);
assert.match(page, /openCopyrightContentPolicy\(\)/);
assert.match(page, /#dashboardSection > nav \{ position:sticky; top:0; z-index:30; \}/);
assert.match(page, /height:calc\(100dvh - 68px\)/);
assert.match(page, /Portal panel sizing audit/);
assert.match(page, /Professional future surface system/);
assert.match(page, /--portal-header-height/);
assert.match(page, /#dashboardSection > \.app-sidebar\.is-collapsed ~ \.container/);
assert.match(page, /#ticketsTab #ticketForm > \.flex-form-row \{[\s\S]*grid-template-columns:repeat\(auto-fit/);
assert.match(page, /@media \(min-width:1920px\) and \(min-height:900px\)/);
assert.match(page, /@media \(min-width:2560px\)/);
assert.match(client, /function observePortalHeaderSize\(\)/);
assert.match(client, /--portal-header-height/);
assert.match(page, /class="guide-records-table"/);
assert.match(page, /data-label="Institution \/ phase"/);
assert.match(page, /@media \(max-width:760px\)[\s\S]*guide-records-table td::before/);
assert.ok(page.indexOf('id="littleFeetCinematicJourney"') > page.indexOf('id="schoolMapContainer"'), 'Cinematic should appear after the practical Home content.');
console.log('Web quality regression test passed.');
